import type { CommandDescriptor } from '../command-kit/command-descriptor-types.js';
import { commandOperation } from '../command-operation.js';
import {
  agentContract,
  collectValues,
  doc,
  fieldClaimFamily,
  fixedClaimContract,
  fixedClaimFamily,
  mixedClaimContract,
  option,
  parseNonNegativeInteger,
  parsePositiveInteger,
  withJsonOption,
} from '../command-kit/command-spec-builders.js';
import { DIFF_IMPACT_BATCH_COMMAND, HEALTH_PHASE_COMMAND } from '../cli-support.js';
import { BUILTIN_SKILLS } from '../setup.js';
import * as handlers from './command-handlers.js';
import { outputContinuationCommandDescriptor } from './output-continuation-command.js';
import { orderedQueryCommandDescriptors } from './query-command-specs.js';

export const commandDescriptors: CommandDescriptor[] = [
  outputContinuationCommandDescriptor,
  {
    id: 'hook-architecture-stop',
    command: 'hook-architecture-stop',
    hidden: true,
    agent: agentContract(
      'Did indexed source changes preserve the repository architecture policy?',
      'architecture policy decision and enforced finding identities',
      [],
      'complete',
      'diff',
      commandOperation('repository-observation'),
    ),
    description: 'Internal architecture-only Stop hook',
    renderShape: 'custom',
    handler: handlers.handleArchitectureStopHook,
  },
  {
    id: 'reindex',
    command: 'reindex',
    agent: agentContract(
      'Can the repository index be refreshed, and which language shards succeeded?',
      'index generation, shard statuses, reuse diagnostics, and failures',
      [],
      'complete',
      'repository',
      commandOperation('composite'),
    ),
    description: 'Index the codebase and convert to SQLite',
    options: withJsonOption([
      option('-l, --language <lang>', 'Index only this language (can be repeated)', collectValues, []),
      option('--pnpm-workspaces', 'Enable pnpm workspace support (TypeScript)'),
      option('--force', 'Rebuild even if source inputs are unchanged'),
      option('--allow-partial', 'Write an incomplete index when one or more detected languages fail'),
      option('--trust-project-tools', 'Permit reviewed indexers from this repository for this run'),
      option('--install-missing', 'Install missing global tools at reviewed immutable versions for this run'),
      option('--indexer-concurrency <n>', 'Number of language indexers to run at once', parsePositiveInteger),
    ]),
    renderShape: 'custom',
    docs: doc('Indexing', ['scip-query reindex']),
    handler: handlers.handleReindex,
  },
  {
    id: 'augment-sources',
    command: 'augment-sources',
    agent: agentContract(
      'Can source files omitted by upstream indexers be added to the index?',
      'added document counts and augmentation status',
      [],
      'complete',
      'repository',
      commandOperation('composite'),
    ),
    description: 'Add source files skipped by upstream SCIP indexers to the SQLite documents table',
    renderShape: 'custom',
    docs: doc('Indexing'),
    handler: handlers.handleAugmentSources,
  },
  {
    id: 'augment-vue',
    command: 'augment-vue',
    agent: agentContract(
      'Can Vue SFC references be compiler-resolved and added to the index?',
      'Vue augmentation counts, project, and diagnostics',
      [],
      'complete',
      'repository',
      commandOperation('composite'),
    ),
    description: 'Add compiler-resolved Vue SFC references to the SQLite index using Volar',
    options: [option('--project <tsconfig>', 'Vue tsconfig path', undefined, 'frontend/tsconfig.scip.json')],
    renderShape: 'custom',
    docs: doc('Indexing'),
    handler: handlers.handleAugmentVue,
  },
  ...orderedQueryCommandDescriptors,
  {
    id: DIFF_IMPACT_BATCH_COMMAND,
    command: DIFF_IMPACT_BATCH_COMMAND,
    description: 'Internal diff-impact batch worker',
    hidden: true,
    options: [
      option('--json', 'Emit the private worker envelope without transport pagination'),
      option('--base <ref>', 'Git ref to diff against (default: HEAD)'),
    ],
    renderShape: 'custom',
    handler: handlers.handleDiffImpactBatch,
  },
  {
    id: 'diff-impact',
    command: 'diff-impact',
    agent: agentContract(
      'Which symbols changed in this diff and which downstream consumers are affected?',
      'changed symbols, downstream consumer identities, and impact paths',
      [],
      'bounded',
      'diff',
    ),
    description: 'Map changed symbols and downstream consumers from the current git diff',
    options: withJsonOption([option('--base <ref>', 'Git ref to diff against (default: HEAD)')]),
    claims: mixedClaimContract(
      ['index-generation', 'live-workspace'],
      [
        fixedClaimFamily('changed-files', 'changedFiles[]', 'repository-source'),
        fixedClaimFamily('changed-symbols', 'changedSymbols[]', 'compiler-graph'),
        fixedClaimFamily('downstream-consumers', 'affected[]', 'compiler-graph'),
      ],
    ),
    renderShape: 'custom',
    docs: doc('Impact'),
    handler: handlers.handleDiffImpact,
  },
  {
    id: HEALTH_PHASE_COMMAND,
    command: HEALTH_PHASE_COMMAND,
    description: 'Internal health phase worker',
    hidden: true,
    arguments: [{ name: '<phase>' }],
    options: [
      option('--json', 'Emit the private worker envelope without transport pagination'),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded candidate analyses on large indexes'),
    ],
    renderShape: 'custom',
    handler: handlers.handleHealthPhase,
  },
  {
    id: 'health',
    command: 'health',
    agent: agentContract(
      'Where has this repository accumulated drift, duplication, complexity, or cleanup pressure?',
      'health score, findings, priorities, baselines, and coverage notes',
      [],
      'bounded',
      'repository',
      commandOperation('repository-observation', [
        { when: { kind: 'option', name: 'writeBaseline', equals: true }, role: 'composite' },
      ]),
    ),
    description: 'Composite repository health report with React, Vue, and general cleanup findings',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded candidate analyses on large indexes'),
      option('--baseline', 'Compare findings against the committed baseline; exit 1 on new findings'),
      option('--write-baseline', 'Snapshot current finding identities to the baseline file'),
    ]),
    claims: mixedClaimContract(
      ['index-generation', 'live-workspace', 'process'],
      [
        fieldClaimFamily('actions', 'actions[]', 'evidence', {
          'graph-fact': 'compiler-graph',
          heuristic: 'heuristic',
          'change-graph': 'change-history',
        }),
        fixedClaimFamily('coverage-notes', 'coverage', 'repository-source'),
      ],
    ),
    renderShape: 'custom',
    docs: doc('Health', ['scip-query health --json', 'scip-query health --baseline']),
    handler: handlers.handleHealth,
  },
  {
    id: 'install-skills',
    command: 'install-skills',
    agent: agentContract(
      'Which scip-query skills were installed, updated, skipped, or conflicted?',
      'skill target paths and install outcomes',
      [],
      'complete',
      'repository',
      commandOperation('mutation'),
    ),
    description: `Install skills (${BUILTIN_SKILLS.join(', ')}) into Claude Code, Codex, and shared agent roots`,
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleInstallSkills,
  },
  {
    id: 'check-deps',
    command: 'check-deps',
    agent: agentContract(
      'Which scip-query and language-indexer dependencies are runnable?',
      'dependency readiness statuses and remediation',
      [],
      'complete',
      'repository',
      commandOperation('environment-observation'),
    ),
    description: 'Check whether scip-query and the detected language indexers are runnable',
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleCheckDeps,
  },
  {
    id: 'capabilities',
    command: 'capabilities',
    agent: agentContract(
      'Which repository-mapping and analysis capabilities are available here?',
      'capability matrix with availability and reasons',
      [],
      'complete',
      'repository',
      commandOperation('environment-observation'),
    ),
    description: 'Report which mapping and analysis capabilities are available in this project',
    options: withJsonOption([option('--matrix', 'Render the project capability matrix (default output)')]),
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleCapabilities,
  },
  {
    id: 'init',
    command: 'init',
    agent: agentContract(
      'Can a starter scip-query configuration be created for this project?',
      'configuration path and creation outcome',
      [],
      'complete',
      'repository',
      commandOperation('mutation'),
    ),
    description: 'Create a .scipquery.json configuration file for this project',
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleInit,
  },
  {
    id: 'config-validate',
    command: 'config-validate',
    agent: agentContract(
      'Is this project configuration valid and internally consistent?',
      'validation diagnostics with configuration paths',
      [],
      'complete',
      'repository',
    ),
    description: 'Validate .scipquery.json, structured suppressions, architecture, and coupling groups',
    options: withJsonOption(),
    claims: fixedClaimContract('repository-source', ['live-workspace']),
    renderShape: 'custom',
    docs: doc('Maintenance', ['scip-query config-validate']),
    handler: handlers.handleConfigValidate,
  },
  {
    id: 'suppress',
    command: 'suppress <id>',
    agent: agentContract(
      'Can this accepted finding be recorded with an auditable reason?',
      'suppression identity, path, scope, and expiry',
      ['finding'],
      'complete',
      undefined,
      commandOperation('mutation'),
    ),
    description: 'Record an accepted finding under .scipquery/suppressions with a required reason',
    options: withJsonOption([
      option('--reason <text>', 'Required concrete claim explaining why the detector remediation is inapplicable'),
      option('--reason-code <code>', 'Required adjudication code'),
      option('--evidence <kind:referent>', 'Required counterevidence; repeat for more evidence', collectValues, []),
      option('--check <check>', 'Optional detector name to narrow the suppression'),
      option('--file <path>', 'Optional file path to narrow the suppression'),
      option('--expires-at <iso>', 'Optional ISO date after which the suppression expires'),
      option('--replace <revision>', 'Replace a prior decision with this exact SHA-256 revision'),
    ]),
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleSuppress,
  },
  {
    id: 'doctor',
    command: 'doctor',
    agent: agentContract(
      'Why is scip-query unhealthy or unavailable in this project?',
      'configuration, freshness, dependency, and capability diagnostics',
      [],
      'complete',
      'repository',
      commandOperation('environment-observation'),
    ),
    description: 'Diagnose configuration, index freshness, dependencies, and project capabilities',
    options: withJsonOption(),
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleDoctor,
  },
  {
    id: 'setup',
    command: 'setup',
    agent: agentContract(
      'Can scip-query be bootstrapped end to end in this project?',
      'setup step outcomes, files, capabilities, smoke tests, and warnings',
      [],
      'complete',
      'repository',
      commandOperation('composite'),
    ),
    description: 'Install skills, write agent guidance, refresh the index, and report repository health',
    options: withJsonOption([
      option('--guided', 'Require and open the interactive terminal checklist'),
      option('--yes', 'Accept recommended setup defaults without prompting'),
      option('--no-skills', 'Skip user-level agent skill installation'),
      option('--no-parsers', 'Skip Tree-sitter AST parser installation and repair'),
      option('--install-missing', 'Install missing global tools at reviewed immutable versions'),
      option('--no-health', 'Skip the optional full health report and dossier'),
      option('--dossier-dir <path>', 'Directory for generated setup health dossier files'),
    ]),
    renderShape: 'custom',
    docs: doc('Maintenance', ['scip-query setup', 'scip-query setup --install-missing', 'scip-query setup --json']),
    handler: handlers.handleSetup,
  },
  {
    id: 'setup-agent',
    command: 'setup-agent',
    agent: agentContract(
      'Can concise project guidance for scip-query be written?',
      'written, unchanged, and skipped agent instruction files',
      [],
      'complete',
      'repository',
      commandOperation('mutation'),
    ),
    description: 'Write concise scip-query mapping and cleanup guidance to AGENTS.md and CLAUDE.md',
    renderShape: 'custom',
    docs: doc('Maintenance', ['scip-query setup-agent']),
    handler: handlers.handleSetupAgent,
  },
  {
    id: 'uninstall',
    command: 'uninstall',
    agent: agentContract(
      'Which scip-query-owned integrations can be removed without touching user-owned files?',
      'removed, retained, skipped, and dry-run targets',
      [],
      'complete',
      'repository',
      commandOperation('mutation', [
        { when: { kind: 'option', name: 'dryRun', equals: true }, role: 'repository-preview' },
      ]),
    ),
    description: 'Remove selected scip-query-owned skills or project guidance',
    options: withJsonOption([
      option('--global', 'Remove scip-query-owned skill symlinks from user-level agent skill roots'),
      option('--project', 'Remove managed AGENTS.md and CLAUDE.md blocks'),
      option('--dry-run', 'List what would be removed without changing files'),
      option('--verbose', 'List every unrelated global skill entry left in place'),
    ]),
    renderShape: 'custom',
    docs: doc('Maintenance', ['scip-query uninstall --dry-run', 'scip-query uninstall --project']),
    handler: handlers.handleUninstall,
  },
  {
    id: 'watch',
    command: 'watch',
    agent: agentContract(
      'What is the watcher doing, or can its background service be started or stopped?',
      'watcher state, generation, activity, and errors',
      [],
      'complete',
      'repository',
      commandOperation('composite', [
        { when: { kind: 'option', name: 'status', equals: true }, role: 'environment-observation' },
      ]),
    ),
    description: 'Watch in the foreground or manage the project refresh service',
    options: withJsonOption([
      option('--daemon', 'Make sure that the background service is running'),
      option('--status', 'Show the watcher state'),
      option('--stop', 'Stop the watcher for this project'),
      option('--debounce <ms>', 'Milliseconds after the last change', parseNonNegativeInteger),
      option('--cooldown <ms>', 'Minimum milliseconds between indexes', parseNonNegativeInteger),
      option('--git-poll <ms>', 'Milliseconds between Git state checks', parseNonNegativeInteger),
      option('--idle-timeout <ms>', 'Milliseconds before a clean idle daemon exits', parseNonNegativeInteger),
    ]),
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleWatch,
  },
  {
    id: 'status',
    command: 'status',
    agent: agentContract(
      'Is the index fresh, complete, and usable for this project?',
      'freshness, generation, language shards, watcher, and optional capabilities',
      [],
      'complete',
      'repository',
      commandOperation('environment-observation'),
    ),
    description: 'Show index status for this project',
    options: withJsonOption([option('--capabilities', 'Include the project capability matrix')]),
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleStatus,
  },
];
