import type { CommandDescriptor, CommandOptionParser } from './command-descriptor-types.js';
import { collect, parseIntSafe, parsePositiveInt } from './cli-context.js';
import { DIFF_IMPACT_BATCH_COMMAND, HEALTH_PHASE_COMMAND } from './cli-support.js';
import { BUILTIN_SKILLS } from './setup.js';
import * as handlers from './command-handlers.js';
import * as queryHandlers from './query-command-handlers.js';

const collectValues = collect as CommandOptionParser;
const parseInteger = parseIntSafe as CommandOptionParser;
const parsePositiveInteger = parsePositiveInt as CommandOptionParser;
const parseNumber = parseFloat as CommandOptionParser;
const parseIntegerLoose = parseInt as CommandOptionParser;

function option(
  flags: string,
  description: string,
  parser?: CommandOptionParser,
  ...defaultValue: [unknown?]
): NonNullable<CommandDescriptor['options']>[number] {
  return defaultValue.length > 0
    ? { flags, description, parser, defaultValue: defaultValue[0] }
    : { flags, description, parser };
}

function doc(category: string, examples: readonly string[] = []): NonNullable<CommandDescriptor['docs']> {
  return { category, examples };
}

export const commandDescriptors: CommandDescriptor[] = [
  {
    id: 'reindex',
    command: 'reindex',
    description: 'Index the codebase and convert to SQLite',
    options: [
      option('-l, --language <lang>', 'Index only this language (can be repeated)', collectValues, []),
      option('--pnpm-workspaces', 'Enable pnpm workspace support (TypeScript)'),
      option('--force', 'Rebuild even if source inputs are unchanged'),
      option('--allow-partial', 'Write an incomplete index when one or more detected languages fail'),
      option('--indexer-concurrency <n>', 'Number of language indexers to run at once', parsePositiveInteger),
    ],
    renderShape: 'custom',
    docs: doc('Indexing', ['scip-query reindex']),
    handler: handlers.handleReindex,
  },
  {
    id: 'augment-sources',
    command: 'augment-sources',
    description: 'Add source files skipped by upstream SCIP indexers to the SQLite documents table',
    renderShape: 'custom',
    docs: doc('Indexing'),
    handler: handlers.handleAugmentSources,
  },
  {
    id: 'augment-vue',
    command: 'augment-vue',
    description: 'Add compiler-resolved Vue SFC references to the SQLite index using Volar',
    options: [option('--project <tsconfig>', 'Vue tsconfig path', undefined, 'frontend/tsconfig.scip.json')],
    renderShape: 'custom',
    docs: doc('Indexing'),
    handler: handlers.handleAugmentVue,
  },
  {
    id: 'stats',
    command: 'stats',
    description: 'Show index statistics',
    renderShape: 'custom',
    docs: doc('Core'),
    handler: queryHandlers.handleStats,
  },
  {
    id: 'files',
    command: 'files <pattern>',
    description: 'Find files matching a pattern',
    renderShape: 'list',
    docs: doc('Navigation', ['scip-query files auth']),
    handler: queryHandlers.handleFiles,
  },
  {
    id: 'symbols',
    command: 'symbols <file>',
    description: 'List symbols defined in a file (with line ranges + signatures)',
    renderShape: 'list',
    docs: doc('Navigation', ['scip-query symbols src/runtime/cli.ts']),
    handler: queryHandlers.handleSymbols,
  },
  {
    id: 'methods',
    command: 'methods <className>',
    description: 'List methods of a class (with line ranges)',
    renderShape: 'list',
    docs: doc('Navigation'),
    handler: queryHandlers.handleMethods,
  },
  {
    id: 'refs',
    command: 'refs <symbol>',
    description: 'Find all files referencing a symbol',
    options: [option('--full', 'Run unbounded semantic analysis on large indexes')],
    budget: 'semantic',
    renderShape: 'grouped-by-file',
    docs: doc('Navigation', ['scip-query refs login']),
    handler: queryHandlers.handleRefs,
  },
  {
    id: 'trace',
    command: 'trace <symbol>',
    description: 'Trace a symbol: definition + all references',
    options: [option('--full', 'Run unbounded semantic analysis on large indexes')],
    budget: 'semantic',
    renderShape: 'sectioned-report',
    docs: doc('Navigation', ['scip-query trace parseSymbol']),
    handler: queryHandlers.handleTrace,
  },
  {
    id: 'deps',
    command: 'deps <file>',
    description: 'Files this file depends on (internal)',
    renderShape: 'list',
    docs: doc('Navigation'),
    handler: queryHandlers.handleDeps,
  },
  {
    id: 'rdeps',
    command: 'rdeps <file>',
    description: 'Files that depend on this file/module',
    renderShape: 'list',
    docs: doc('Navigation'),
    handler: queryHandlers.handleRdeps,
  },
  {
    id: 'system',
    command: 'system <module>',
    description: 'Full module map: files, symbols, deps in/out',
    renderShape: 'sectioned-report',
    docs: doc('Navigation', ['scip-query system queries']),
    handler: queryHandlers.handleSystem,
  },
  {
    id: 'surface',
    command: 'surface <module>',
    description: 'What symbols consumers actually use from this module',
    renderShape: 'list',
    docs: doc('Navigation'),
    handler: queryHandlers.handleSurface,
  },
  {
    id: 'dead',
    command: 'dead [scope]',
    description: 'Find dead code and file-internal symbols (no cross-file consumers)',
    options: [
      option('--min-loc <n>', 'Only show symbols >= N lines', parseInteger, 1),
      option('--include-tests', 'Include test files'),
      option('--skip-barrels', 'Ignore refs from barrel re-export files'),
      option('--include-members', 'Include class members'),
      option('--only-dead', 'Show only [dead code] symbols (skip [file-internal only])'),
      option('--only-internal', 'Show only [file-internal only] symbols (skip [dead code])'),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query dead --min-loc 10']),
    handler: queryHandlers.handleDead,
  },
  {
    id: 'hotspots',
    command: 'hotspots',
    description: 'Most-referenced symbols in the codebase (choke points)',
    options: [
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('-s, --scope <path>', 'Limit to files matching path'),
    ],
    renderShape: 'table',
    docs: doc('Graph'),
    handler: queryHandlers.handleHotspots,
  },
  {
    id: 'imports',
    command: 'imports <file>',
    description: 'What symbols does this file import?',
    options: [option('--full', 'Run unbounded semantic analysis on large indexes')],
    budget: 'semantic',
    renderShape: 'list',
    docs: doc('Navigation'),
    handler: queryHandlers.handleImports,
  },
  {
    id: 'imported-by',
    command: 'imported-by <symbol>',
    description: 'Which files import this symbol?',
    renderShape: 'list',
    docs: doc('Navigation'),
    handler: queryHandlers.handleImportedBy,
  },
  {
    id: 'unused-imports',
    command: 'unused-imports <file>',
    description: 'Find imports not referenced in the same file',
    options: [option('--full', 'Run unbounded semantic analysis on large indexes')],
    budget: 'semantic',
    renderShape: 'list',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleUnusedImports,
  },
  {
    id: 'outline',
    command: 'outline <file>',
    description: 'Tree view of symbols in a file (using nesting hierarchy)',
    renderShape: 'custom',
    docs: doc('Navigation'),
    handler: queryHandlers.handleOutline,
  },
  {
    id: 'members',
    command: 'members <symbol>',
    description: 'All children of a symbol (methods, fields, nested types)',
    renderShape: 'list',
    docs: doc('Navigation'),
    handler: queryHandlers.handleMembers,
  },
  {
    id: 'fan-in',
    command: 'fan-in [symbol]',
    description: 'How many files reference a symbol (or top fan-in across codebase)',
    options: [
      option('-n, --limit <n>', 'Number of results for top mode', parseInteger, 30),
      option('-s, --scope <path>', 'Limit to files matching path'),
    ],
    renderShape: 'custom',
    docs: doc('Graph'),
    handler: queryHandlers.handleFanIn,
  },
  {
    id: 'fan-out',
    command: 'fan-out [file]',
    description: 'How many external symbols a file uses (or top fan-out across codebase)',
    options: [
      option('-n, --limit <n>', 'Number of results for top mode', parseInteger, 30),
      option('-s, --scope <path>', 'Limit to files matching path'),
    ],
    renderShape: 'custom',
    docs: doc('Graph'),
    handler: queryHandlers.handleFanOut,
  },
  {
    id: 'coupling',
    command: 'coupling [file1] [file2]',
    description: 'Coupling between two files, or top coupled pairs in codebase',
    options: [
      option('-n, --limit <n>', 'Number of results for top mode', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
    ],
    renderShape: 'custom',
    docs: doc('Graph'),
    handler: queryHandlers.handleCoupling,
  },
  {
    id: 'cycles',
    command: 'cycles',
    description: 'Detect circular dependency chains between files',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--max-depth <n>', 'Maximum cycle depth', parseInteger, 10),
    ],
    renderShape: 'custom',
    docs: doc('Graph'),
    handler: queryHandlers.handleCycles,
  },
  {
    id: 'bottlenecks',
    command: 'bottlenecks',
    description: 'Find coupling hubs: high fan-in AND high fan-out',
    options: [
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-fan-in <n>', 'Minimum fan-in', parseInteger, 2),
      option('--min-fan-out <n>', 'Minimum fan-out', parseInteger, 2),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    budget: 'candidate-scan',
    renderShape: 'table',
    docs: doc('Graph'),
    handler: queryHandlers.handleBottlenecks,
  },
  {
    id: 'isolated',
    command: 'isolated',
    description: 'Find completely orphaned symbols (no references at all)',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum lines of code', parseInteger, 3),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    budget: 'candidate-scan',
    renderShape: 'grouped-by-file',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleIsolated,
  },
  {
    id: 'by-kind',
    command: 'by-kind <kind>',
    description: 'Find symbols by SCIP kind (class, interface, enum, function, etc.)',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 100),
    ],
    renderShape: 'list',
    docs: doc('Navigation'),
    handler: queryHandlers.handleByKind,
  },
  {
    id: 'kind-counts',
    command: 'kind-counts',
    description: 'Histogram of symbol kinds in the codebase',
    options: [option('-s, --scope <path>', 'Limit to files matching path')],
    renderShape: 'table',
    docs: doc('Navigation'),
    handler: queryHandlers.handleKindCounts,
  },
  {
    id: 'deep-chains',
    command: 'deep-chains',
    description: 'Find the longest transitive dependency chains',
    options: [
      option('-n, --limit <n>', 'Number of chains to show', parseInteger, 10),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-depth <n>', 'Minimum chain depth', parseInteger, 3),
    ],
    renderShape: 'custom',
    docs: doc('Graph'),
    handler: queryHandlers.handleDeepChains,
  },
  {
    id: 'hierarchy',
    command: 'hierarchy <symbol>',
    description: 'Show a symbol\'s ancestry chain (method → class → module)',
    renderShape: 'list',
    docs: doc('Navigation'),
    handler: queryHandlers.handleHierarchy,
  },
  {
    id: 'call-graph',
    command: 'call-graph <symbol>',
    description: 'Show incoming callers and outgoing callees for a symbol',
    options: [option('--full', 'Run unbounded semantic analysis on large indexes')],
    budget: 'semantic',
    renderShape: 'sectioned-report',
    docs: doc('Graph'),
    handler: queryHandlers.handleCallGraph,
  },
  {
    id: 'similar',
    command: 'similar [symbol]',
    description: 'Find heuristic function similarity candidates from callee fingerprints',
    options: [
      option('--min-similarity <n>', 'Minimum Jaccard similarity (0-1)', parseNumber, 0.4),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-callees <n>', 'Minimum callees to consider', parseInteger, 4),
      option('--cross-file-only', 'Only show cross-file pairs (skip same-file matches)'),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    heuristic: { label: 'similarity candidates' },
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleSimilar,
  },
  {
    id: 'similar-files',
    command: 'similar-files [file]',
    description: 'Find heuristic similar-file candidates from dependency profiles',
    options: [
      option('--min-similarity <n>', 'Minimum Jaccard similarity (0-1)', parseNumber, 0.5),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-deps <n>', 'Minimum dependencies to consider', parseInteger),
    ],
    heuristic: { label: 'similar file candidates' },
    renderShape: 'custom',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleSimilarFiles,
  },
  {
    id: 'similar-chains',
    command: 'similar-chains',
    description: 'Find heuristic similar-chain candidates from dependency flows',
    options: [
      option('--min-similarity <n>', 'Minimum chain similarity (0-1)', parseNumber, 0.5),
      option('-n, --limit <n>', 'Number of results', parseInteger, 15),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-length <n>', 'Minimum chain length', parseInteger, 3),
      option('--max-length <n>', 'Maximum chain length', parseInteger, 8),
    ],
    heuristic: { label: 'similar chain candidates' },
    renderShape: 'custom',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleSimilarChains,
  },
  {
    id: 'extract-candidates',
    command: 'extract-candidates',
    description: 'Find heuristic extraction candidates from isolated callee clusters',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum function LOC', parseInteger, 10),
      option('--min-callees <n>', 'Minimum callees to analyze', parseInteger, 6),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    heuristic: { label: 'extraction candidates' },
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleExtractCandidates,
  },
  {
    id: 'affected',
    command: 'affected <symbol>',
    description: 'Transitive closure of symbols that could break if this symbol changes',
    options: [
      option('--max-depth <n>', 'Maximum traversal depth', parseInteger, 5),
      option('-s, --scope <path>', 'Limit to files matching path'),
    ],
    renderShape: 'custom',
    docs: doc('Impact'),
    handler: queryHandlers.handleAffected,
  },
  {
    id: 'change-surface',
    command: 'change-surface <file>',
    description: 'Pre-change briefing: exports, consumers, and blast-radius risk',
    options: [option('--full', 'Run unbounded semantic analysis on large indexes')],
    budget: 'semantic',
    renderShape: 'list',
    docs: doc('Impact'),
    handler: queryHandlers.handleChangeSurface,
  },
  {
    id: DIFF_IMPACT_BATCH_COMMAND,
    command: DIFF_IMPACT_BATCH_COMMAND,
    description: 'Internal diff-impact batch worker',
    hidden: true,
    options: [option('--base <ref>', 'Git ref to diff against (default: HEAD)')],
    renderShape: 'custom',
    handler: handlers.handleDiffImpactBatch,
  },
  {
    id: 'diff-impact',
    command: 'diff-impact',
    description: 'Compute changed symbols and downstream consumers from current git diff',
    options: [option('--base <ref>', 'Git ref to diff against (default: HEAD)')],
    renderShape: 'custom',
    docs: doc('Impact'),
    handler: handlers.handleDiffImpact,
  },
  {
    id: 'drift',
    command: 'drift [module]',
    description: 'Detect heuristic drift candidates: unused imports, layer violations, and pattern deviations',
    options: [
      option('--min-deviation <n>', 'Minimum sibling files before reporting unique dependency deviations', parsePositiveInteger, 5),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    heuristic: { label: 'drift candidates' },
    budget: 'semantic',
    renderShape: 'grouped-by-file',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleDrift,
  },
  {
    id: 'wrapper-candidates',
    command: 'wrapper-candidates',
    description: 'Find heuristic wrapper candidates only called by one consumer',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--max-loc <n>', 'Maximum LOC for candidates', parseInteger, 15),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    heuristic: { label: 'wrapper candidates' },
    budget: 'candidate-scan',
    renderShape: 'list',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleWrapperCandidates,
  },
  {
    id: 'passthrough-candidates',
    command: 'passthrough-candidates',
    description: 'Find heuristic passthrough candidates that forward to one callee',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--max-loc <n>', 'Maximum LOC for candidates', parseInteger, 15),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    heuristic: { label: 'passthrough candidates' },
    budget: 'candidate-scan',
    renderShape: 'list',
    docs: doc('Cleanup'),
    handler: queryHandlers.handlePassthroughCandidates,
  },
  {
    id: 'stale-abstractions',
    command: 'stale-abstractions',
    description: 'Find heuristic stale abstraction candidates with 0-1 consumers',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum LOC', parseInteger, 3),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--include-low-confidence', 'Include 1-consumer classes (usually encapsulation, not stale)', undefined, false),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    heuristic: { label: 'stale abstraction candidates' },
    budget: 'candidate-scan',
    renderShape: 'list',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleStaleAbstractions,
  },
  {
    id: 'complexity-hotspots',
    command: 'complexity-hotspots',
    description: 'Find heuristic complexity hotspot candidates from LOC x fan-in x fan-out',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum LOC', parseInteger, 10),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    heuristic: { label: 'complexity hotspot candidates' },
    budget: 'candidate-scan',
    renderShape: 'table',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleComplexityHotspots,
  },
  {
    id: HEALTH_PHASE_COMMAND,
    command: HEALTH_PHASE_COMMAND,
    description: 'Internal health phase worker',
    hidden: true,
    arguments: [{ name: '<phase>' }],
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded candidate analyses on large indexes'),
    ],
    renderShape: 'custom',
    handler: handlers.handleHealthPhase,
  },
  {
    id: 'health',
    command: 'health',
    description: 'Composite codebase health report with prioritized action list',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded candidate analyses on large indexes'),
      option('--json', 'Output as JSON for programmatic consumption'),
    ],
    renderShape: 'custom',
    docs: doc('Health', ['scip-query health --json']),
    handler: handlers.handleHealth,
  },
  {
    id: 'convergence',
    command: 'convergence <symbol1> <symbol2>',
    description: 'Show what a consolidated version of two similar functions would look like',
    options: [option('--full', 'Run unbounded semantic analysis on large indexes')],
    budget: 'semantic',
    renderShape: 'custom',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleConvergence,
  },
  {
    id: 'code',
    command: 'code <symbol>',
    description: 'Read the source code for a symbol (bounded to its definition range)',
    options: [option('-C, --context <n>', 'Extra lines of context above/below', parseInteger, 0)],
    renderShape: 'custom',
    docs: doc('Navigation'),
    handler: queryHandlers.handleCode,
  },
  {
    id: 'complexity',
    command: 'complexity <symbol>',
    description: 'Per-symbol complexity: branches, cyclomatic estimate, fan-in/out, callees',
    options: [option('--full', 'Run unbounded semantic analysis on large indexes')],
    budget: 'semantic',
    renderShape: 'custom',
    docs: doc('Health'),
    handler: queryHandlers.handleComplexity,
  },
  {
    id: 'dataflow',
    command: 'dataflow <symbol>',
    description: 'Reference-level dataflow: definition sites, usage sites, producers, consumers',
    options: [option('--full', 'Run unbounded semantic analysis on large indexes')],
    budget: 'semantic',
    renderShape: 'custom',
    docs: doc('Navigation'),
    handler: queryHandlers.handleDataflow,
  },
  {
    id: 'slice',
    command: 'slice <symbol>',
    description: 'Reference-level program slice: what affects this (backward) or what this affects (forward)',
    options: [
      option('--forward', 'Forward slice (what does this affect). Default is backward.'),
      option('--depth <n>', 'Max transitive depth for backward slice', parseInteger, 3),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    budget: 'semantic',
    renderShape: 'custom',
    docs: doc('Navigation'),
    handler: queryHandlers.handleSlice,
  },
  {
    id: 'install-skills',
    command: 'install-skills',
    description: `Install skills (${BUILTIN_SKILLS.join(', ')}) into Claude Code and Codex`,
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleInstallSkills,
  },
  {
    id: 'check-deps',
    command: 'check-deps',
    description: 'Check whether scip-query and the detected language indexers are actually runnable',
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleCheckDeps,
  },
  {
    id: 'redundant-reexports',
    command: 'redundant-reexports',
    description: 'Find barrel re-exports that nobody imports through',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
    ],
    renderShape: 'grouped-by-file',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleRedundantReexports,
  },
  {
    id: 'similar-signatures',
    command: 'similar-signatures',
    description: 'Find functions with near-identical type signatures (same shape)',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum LOC per function', parseInteger, 3),
      option('-n, --limit <n>', 'Number of groups', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ],
    budget: 'candidate-scan',
    renderShape: 'list',
    docs: doc('Cleanup'),
    handler: queryHandlers.handleSimilarSignatures,
  },
  {
    id: 'init',
    command: 'init',
    description: 'Create a .scipquery.json config file for this project',
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleInit,
  },
  {
    id: 'watch',
    command: 'watch',
    description: 'Watch for file changes and reindex automatically',
    options: [
      option('--debounce <ms>', 'Ms to wait after last change (default: 30000)', parseIntegerLoose),
      option('--cooldown <ms>', 'Min ms between reindexes (default: 60000)', parseIntegerLoose),
    ],
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleWatch,
  },
  {
    id: 'status',
    command: 'status',
    description: 'Show index status for this project',
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleStatus,
  },
];
