import type { CommandDescriptor } from './command-descriptor-types.js';
import { collectValues, doc, option, parseIntegerLoose, parsePositiveInteger, withJsonOption } from './command-spec-builders.js';
import { DIFF_IMPACT_BATCH_COMMAND, HEALTH_PHASE_COMMAND } from './cli-support.js';
import { BUILTIN_SKILLS } from './setup.js';
import * as handlers from './command-handlers.js';
import { queryCommandDescriptor as query } from './query-command-specs.js';

export const commandDescriptors: CommandDescriptor[] = [
  {
    id: 'reindex',
    command: 'reindex',
    description: 'Index the codebase and convert to SQLite',
    options: [
      option('-l, --language <lang>', 'Index only this language (can be repeated)', collectValues, []),
      option('--pnpm-workspaces', 'Enable pnpm workspace support (TypeScript)'),
      option('--force', 'Rebuild even if source inputs are unchanged'),
      option('--allow-partial', 'Write an incomplete index when one or more detected languages fail'),
      option('--indexer-concurrency <n>', 'Number of language indexers to run at once', parsePositiveInteger),
    ],
    renderShape: 'custom',
    docs: doc('Indexing', ['scip-query reindex']),
    handler: handlers.handleReindex,
  },
  {
    id: 'augment-sources',
    command: 'augment-sources',
    description: 'Add source files skipped by upstream SCIP indexers to the SQLite documents table',
    renderShape: 'custom',
    docs: doc('Indexing'),
    handler: handlers.handleAugmentSources,
  },
  {
    id: 'augment-vue',
    command: 'augment-vue',
    description: 'Add compiler-resolved Vue SFC references to the SQLite index using Volar',
    options: [option('--project <tsconfig>', 'Vue tsconfig path', undefined, 'frontend/tsconfig.scip.json')],
    renderShape: 'custom',
    docs: doc('Indexing'),
    handler: handlers.handleAugmentVue,
  },
  query('stats'),
  query('files'),
  query('methods'),
  query('refs'),
  query('trace'),
  query('deps'),
  query('rdeps'),
  query('system'),
  query('surface'),
  query('dead'),
  query('hotspots'),
  query('imports'),
  query('imported-by'),
  query('unused-imports'),
  query('outline'),
  query('members'),
  query('fan-in'),
  query('fan-out'),
  query('coupling'),
  query('cycles'),
  query('bottlenecks'),
  query('isolated'),
  query('by-kind'),
  query('kind-counts'),
  query('deep-chains'),
  query('hierarchy'),
  query('call-graph'),
  query('similar'),
  query('similar-files'),
  query('react-component-duplicates'),
  query('react-hook-candidates'),
  query('react-large-component-pressure'),
  query('vue-component-duplicates'),
  query('vue-composable-candidates'),
  query('vue-large-view-pressure'),
  query('similar-chains'),
  query('extract-candidates'),
  query('affected'),
  query('change-surface'),
  query('cleanup-plan'),
  query('cleanup-apply'),
  query('co-change'),
  query('recent-duplicates'),
  query('doc-drift'),
  query('unused-params'),
  query('diff-gate'),
  query('incomplete-migration'),
  query('plan-context'),
  {
    id: DIFF_IMPACT_BATCH_COMMAND,
    command: DIFF_IMPACT_BATCH_COMMAND,
    description: 'Internal diff-impact batch worker',
    hidden: true,
    options: [option('--base <ref>', 'Git ref to diff against (default: HEAD)')],
    renderShape: 'custom',
    handler: handlers.handleDiffImpactBatch,
  },
  {
    id: 'diff-impact',
    command: 'diff-impact',
    description: 'Compute changed symbols and downstream consumers from current git diff',
    options: [option('--base <ref>', 'Git ref to diff against (default: HEAD)')],
    renderShape: 'custom',
    docs: doc('Impact'),
    handler: handlers.handleDiffImpact,
  },
  query('drift'),
  query('wrapper-candidates'),
  query('passthrough-candidates'),
  query('stale-abstractions'),
  query('complexity-hotspots'),
  query('self-audit'),
  {
    id: HEALTH_PHASE_COMMAND,
    command: HEALTH_PHASE_COMMAND,
    description: 'Internal health phase worker',
    hidden: true,
    arguments: [{ name: '<phase>' }],
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded candidate analyses on large indexes'),
    ],
    renderShape: 'custom',
    handler: handlers.handleHealthPhase,
  },
  {
    id: 'health',
    command: 'health',
    description: 'Composite codebase health report with prioritized action list',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded candidate analyses on large indexes'),
      option('--json', 'Output as JSON for programmatic consumption'),
      option('--baseline', 'Compare findings against the committed baseline; exit 1 on new findings'),
      option('--write-baseline', 'Snapshot current finding identities to the baseline file'),
    ],
    renderShape: 'custom',
    docs: doc('Health', ['scip-query health --json', 'scip-query health --baseline']),
    handler: handlers.handleHealth,
  },
  query('convergence'),
  query('code'),
  query('complexity'),
  query('dataflow'),
  query('slice'),
  {
    id: 'install-skills',
    command: 'install-skills',
    description: `Install skills (${BUILTIN_SKILLS.join(', ')}) into Claude Code, Codex, and shared agent roots`,
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleInstallSkills,
  },
  {
    id: 'check-deps',
    command: 'check-deps',
    description: 'Check whether scip-query and the detected language indexers are actually runnable',
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleCheckDeps,
  },
  {
    id: 'capabilities',
    command: 'capabilities',
    description: 'Report which evidence and verification capabilities are available in this project',
    options: [option('--json', 'Output as JSON for programmatic consumption')],
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleCapabilities,
  },
  {
    id: 'capability-matrix',
    command: 'capability-matrix',
    description: 'Report the evidence and verification capability matrix by language',
    options: [option('--json', 'Output as JSON for programmatic consumption')],
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleCapabilityMatrix,
  },
  query('redundant-reexports'),
  query('similar-signatures'),
  {
    id: 'init',
    command: 'init',
    description: 'Create a .scipquery.json config file for this project',
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleInit,
  },
  {
    id: 'config-validate',
    command: 'config-validate',
    description: 'Validate .scipquery.json, including structured suppressions and declared coupling groups',
    options: [option('--json', 'Output as JSON for programmatic consumption')],
    renderShape: 'custom',
    docs: doc('Maintenance', ['scip-query config-validate']),
    handler: handlers.handleConfigValidate,
  },
  {
    id: 'suppress',
    command: 'suppress <id>',
    description: 'Record an accepted finding in .scipquery.json with a required reason',
    options: withJsonOption([
      option('--reason <text>', 'Required human reason for accepting the finding'),
      option('--check <check>', 'Optional detector/check name to narrow the suppression'),
      option('--file <path>', 'Optional file path to narrow the suppression'),
      option('--expires-at <iso>', 'Optional ISO date after which the suppression expires'),
    ]),
    renderShape: 'custom',
    docs: doc('Maintenance', ['scip-query suppress SQABC123DEF456 --reason "intentional boundary"']),
    handler: handlers.handleSuppress,
  },
  {
    id: 'doctor',
    command: 'doctor',
    description: 'Diagnose config, index freshness, dependency readiness, and project capabilities',
    options: [option('--json', 'Output as JSON for programmatic consumption')],
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleDoctor,
  },
  {
    id: 'setup-agent',
    command: 'setup-agent',
    description: 'Seed agent guidance for this project: AGENTS.md/CLAUDE.md block pointing agents at the scip-query skills and diff gate, plus an optional git pre-commit backstop',
    options: [option('--git-hook', 'Also install a git pre-commit hook that runs diff-gate')],
    renderShape: 'custom',
    docs: doc('Maintenance', ['scip-query setup-agent', 'scip-query setup-agent --git-hook']),
    handler: handlers.handleSetupAgent,
  },
  {
    id: 'setup-ci',
    command: 'setup-ci',
    description: 'Write a GitHub Actions workflow that runs scip-query reindex and diff-gate on pull requests',
    options: [
      option('--force', 'Overwrite an existing workflow'),
      option('--dry-run', 'Print the workflow without writing it'),
    ],
    renderShape: 'custom',
    docs: doc('Maintenance', ['scip-query setup-ci']),
    handler: handlers.handleSetupCi,
  },
  {
    id: 'watch',
    command: 'watch',
    description: 'Watch for file changes and reindex automatically',
    options: [
      option('--debounce <ms>', 'Ms to wait after last change (default: 30000)', parseIntegerLoose),
      option('--cooldown <ms>', 'Min ms between reindexes (default: 60000)', parseIntegerLoose),
    ],
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleWatch,
  },
  {
    id: 'status',
    command: 'status',
    description: 'Show index status for this project',
    options: [
      option('--json', 'Output as JSON for programmatic consumption'),
      option('--capabilities', 'Include the project capability matrix'),
    ],
    renderShape: 'custom',
    docs: doc('Maintenance'),
    handler: handlers.handleStatus,
  },
];
