// Generated by scripts/render-command-reference.ts. Do not edit by hand.
// prettier-ignore
export const GENERATED_AGENT_COMMAND_CATALOG = [
  '- `scip-query system --source [module]` — Module files and dependencies; --source adds a first-use inventory, exports, policy and findings without an index',
  '- `scip-query context <target>` — Compiler-backed context for a symbol, file, or module',
  '- `scip-query evidence` — Traverse selected typed relationships around exact referents; recover source separately when needed',
  '- `scip-query health` — Find concrete TS/JS complexity, duplication, and dependency issues without an index',
  '- `scip-query review` — Review current TS/JS changes against a Git commit, including new and untracked functions',
  '- `scip-query diff-impact` — Map changed symbols and downstream consumers from the current git diff',
  '- `scip-query architecture` — Evaluate project-owned architectural boundaries and dependency rules',
  '- Use `capabilities --matrix` only when a named claim depends on uncertain provider support.',
] as const;

// prettier-ignore
export const GENERATED_EXPLORATION_CONTROLS = [
  {
    "stage": "locate",
    "id": "search",
    "command": "search <exact-text>",
    "question": "Where does this exact text occur in current project text, and which aligned compiler symbol owns each line?",
    "requiredInput": "One exact text literal or deliberately bounded regular expression; insert `--` before a literal that starts with a dash.",
    "returnedFact": "exact cardinality, bounded identities and source, and scope commands that recover withheld matches",
    "evidenceCeiling": "Exact current-text cardinality and locations within reported text coverage; compiler ownership only where aligned.",
    "nonClaim": "Structural source ranking orders exact matches but does not establish task relevance. A literal co-occurrence does not establish a graph relationship.",
    "outputCost": "small",
    "contrasts": [
      "outline: search locates exact text across files; outline enumerates compiler-owned constructs in one known file."
    ],
    "gapClosingCommands": [
      "evidence",
      "inspect",
      "code"
    ]
  },
  {
    "stage": "locate",
    "id": "outline",
    "command": "outline <file>",
    "question": "What symbols and nesting exist in this file?",
    "requiredInput": "One exact current project file path.",
    "returnedFact": "symbol names, nesting, and line ranges",
    "evidenceCeiling": "Exact compiler-owned constructs and ranges when the file is indexed; no invented semantic overlay.",
    "nonClaim": "File ownership and nesting do not establish execution or task relevance.",
    "outputCost": "small",
    "contrasts": [
      "search: outline enumerates constructs in one known file; search locates exact text across current project text.",
      "code: outline returns identities and ranges; code materializes exact source for selected identities."
    ],
    "gapClosingCommands": [
      "evidence",
      "inspect",
      "code"
    ]
  },
  {
    "stage": "locate",
    "id": "entrypoints",
    "command": "entrypoints [text]",
    "question": "Which detected external roots or entry-surface candidates match this text?",
    "requiredInput": "Optional exact text to filter candidates; otherwise the current indexed repository.",
    "returnedFact": "entry symbols with files, confidence, evidence, and observed static caller counts",
    "evidenceCeiling": "Source/compiler-grounded entry evidence and observed static caller counts; exported-only candidates remain candidates.",
    "nonClaim": "A package-public export or zero indexed callers is an entry candidate, not proof of runtime ingress. Entry classification does not establish that the callable executes.",
    "outputCost": "bounded",
    "contrasts": [
      "entry-map: entrypoints locates possible external roots; entry-map traverses static calls from one selected root.",
      "search: entrypoints classifies callable roots; search only locates exact text and ownership."
    ],
    "gapClosingCommands": [
      "evidence",
      "inspect",
      "code"
    ]
  },
  {
    "stage": "project",
    "id": "evidence",
    "command": "evidence",
    "question": "Which exact execution, runtime, data, state, temporal, contract, identity, ownership, or dependency relationships surround these referents? Which related source must be read only when graph evidence leaves a named implementation gap?",
    "requiredInput": "One or more exact symbol, file:line, or literal roots plus explicit family, direction, depth, and output bound.",
    "returnedFact": "batched exact selectors and typed graph relationships; compact endpoints with exact locations and follow-up commands; coverage and recoverable omissions; exact source-recovery command when source was requested with a graph projection; explicit ambiguity failure with exact rerun commands",
    "evidenceCeiling": "Typed edges only to each registered provider ceiling within the explicitly selected projection and reported coverage.",
    "nonClaim": "The projection does not infer which relationships are relevant to the user task. Reference, dependency, data, state, temporal, contract, and identity edges do not become execution claims.",
    "outputCost": "bounded",
    "contrasts": [
      "refs: refs enumerates direct reference sites; evidence traverses explicitly selected typed relationships.",
      "call-graph: call-graph specializes in static calls; evidence can combine execution with other selected families.",
      "dependence-slice: dependence-slice computes a program-dependence slice; evidence performs bounded graph projection."
    ],
    "gapClosingCommands": [
      "inspect",
      "code"
    ]
  },
  {
    "stage": "read",
    "id": "inspect",
    "command": "inspect",
    "question": "Which related source units across several known text, symbol, or location anchors should be read together?",
    "requiredInput": "One or more exact text, symbol, or file:line selectors naming the unresolved behavior.",
    "returnedFact": "one ranked, deduplicated semantic packet plus exact selector cardinality and explicit expansion coverage",
    "evidenceCeiling": "Complete current source for every materialized syntax unit; bounded selector and packet coverage remain explicit.",
    "nonClaim": "A source packet does not choose which implementation details are relevant to the user task. A reference mention does not establish executable reachability.",
    "outputCost": "potentially-large",
    "contrasts": [
      "code: inspect batches bounded behavior or source gaps; code materializes complete exact source.",
      "evidence: inspect reads implementation units; evidence projects typed relationships without source."
    ],
    "gapClosingCommands": []
  },
  {
    "stage": "read",
    "id": "code",
    "command": "code <selectors...>",
    "question": "What exact source defines these symbols, ranges, or file surfaces?",
    "requiredInput": "One or more exact symbols, file:line ranges, or file paths.",
    "returnedFact": "per-selector resolution, complete definition source, exact ranges, optional same-file call closure, file export surfaces, and omitted-local ledgers",
    "evidenceCeiling": "Exact current source bytes for every resolved selector, with omitted file-local constructs disclosed.",
    "nonClaim": "Source materialization does not establish callers, runtime reachability, or task relevance by itself.",
    "outputCost": "potentially-large",
    "contrasts": [
      "inspect: code materializes complete exact source; inspect batches bounded behavior or source gaps.",
      "outline: code reads selected implementations; outline enumerates file structure without reading every body."
    ],
    "gapClosingCommands": []
  }
] as const;
