// Generated by scripts/render-command-reference.ts. Do not edit by hand.
// prettier-ignore
export const GENERATED_AGENT_COMMAND_CATALOG = [
  '- `scip-query search <exact-text>` — Where does this exact text occur in current project text, and which aligned compiler symbol owns each line? Requires: One exact text literal or deliberately bounded regular expression.',
  '- `scip-query outline <file>` — What symbols and nesting exist in this file? Requires: One exact current project file path.',
  '- `scip-query entrypoints [text]` — Which detected external roots or entry-surface candidates match this text? Requires: Optional exact text to filter candidates; otherwise the current indexed repository.',
  '- `scip-query evidence` — Which exact execution, runtime, data, state, temporal, contract, identity, ownership, or dependency relationships surround these referents? Which related source must be read only when graph evidence leaves a named implementation gap? Requires: One or more exact symbol, file:line, or literal roots plus explicit family, direction, depth, and output bound.',
  '- `scip-query inspect` — Which related source units across several known text, symbol, or location anchors should be read together? Requires: One or more exact text, symbol, or file:line selectors naming the unresolved behavior.',
  '- `scip-query code <selectors...>` — What exact source defines these symbols, ranges, or file surfaces? Requires: One or more exact symbols, file:line ranges, or file paths.',
  '- Choose graph controls explicitly: `execution incoming` — Who can call or reach this?; `execution outgoing` — What can this call or reach?; `dataflow incoming` — Where can this value come from?; `dataflow outgoing` — Where can this value go?; `runtime both` — Which producer and consumer rendezvous?; `state both` — What resource is observed or changed?; `temporal both` — What occurs before or after this?; `contract both` — What interface constrains this?; `identity both` — Are these observations the same entity?; `ownership both` — What contains or owns this?; `dependencies outgoing` — What does this statically rely on?. The CLI does not infer them from English intent.',
  '- Calibration: exact is directly observed; derived is deterministically computed; candidate needs confirmation; mixed discloses its constituents; unknown cannot support a stronger claim. Read coverage and recovery before making absence claims.',
  '- Run `scip-query capabilities` for the complete evidence ceilings, non-claims, contrasts, and current provider support.',
] as const;

// prettier-ignore
export const GENERATED_EXPLORATION_CONTROLS = [
  {
    "stage": "locate",
    "id": "search",
    "command": "search <exact-text>",
    "question": "Where does this exact text occur in current project text, and which aligned compiler symbol owns each line?",
    "requiredInput": "One exact text literal or deliberately bounded regular expression.",
    "returnedFact": "exact cardinality, bounded identities and source, and scope commands that recover withheld matches",
    "evidenceCeiling": "Exact current-text cardinality and locations within reported text coverage; compiler ownership only where aligned.",
    "nonClaim": "Structural source ranking orders exact matches but does not establish task relevance. A literal co-occurrence does not establish a graph relationship.",
    "outputCost": "small",
    "contrasts": [
      "outline: search locates exact text across files; outline enumerates compiler-owned constructs in one known file."
    ],
    "gapClosingCommands": [
      "evidence",
      "inspect",
      "code"
    ]
  },
  {
    "stage": "locate",
    "id": "outline",
    "command": "outline <file>",
    "question": "What symbols and nesting exist in this file?",
    "requiredInput": "One exact current project file path.",
    "returnedFact": "symbol names, nesting, and line ranges",
    "evidenceCeiling": "Exact compiler-owned constructs and ranges when the file is indexed; no invented semantic overlay.",
    "nonClaim": "File ownership and nesting do not establish execution or task relevance.",
    "outputCost": "small",
    "contrasts": [
      "search: outline enumerates constructs in one known file; search locates exact text across current project text.",
      "code: outline returns identities and ranges; code materializes exact source for selected identities."
    ],
    "gapClosingCommands": [
      "evidence",
      "inspect",
      "code"
    ]
  },
  {
    "stage": "locate",
    "id": "entrypoints",
    "command": "entrypoints [text]",
    "question": "Which detected external roots or entry-surface candidates match this text?",
    "requiredInput": "Optional exact text to filter candidates; otherwise the current indexed repository.",
    "returnedFact": "entry symbols with files, confidence, evidence, and indexed caller counts",
    "evidenceCeiling": "Source/compiler-grounded entry evidence and indexed caller counts; exported-only candidates remain candidates.",
    "nonClaim": "A package-public export or zero indexed callers is an entry candidate, not proof of runtime ingress. Entry classification does not establish that the callable executes.",
    "outputCost": "bounded",
    "contrasts": [
      "entry-map: entrypoints locates possible external roots; entry-map traverses static calls from one selected root.",
      "search: entrypoints classifies callable roots; search only locates exact text and ownership."
    ],
    "gapClosingCommands": [
      "evidence",
      "inspect",
      "code"
    ]
  },
  {
    "stage": "project",
    "id": "evidence",
    "command": "evidence",
    "question": "Which exact execution, runtime, data, state, temporal, contract, identity, ownership, or dependency relationships surround these referents? Which related source must be read only when graph evidence leaves a named implementation gap?",
    "requiredInput": "One or more exact symbol, file:line, or literal roots plus explicit family, direction, depth, and output bound.",
    "returnedFact": "batched exact selectors and typed graph relationships; compact endpoints with exact locations and follow-up commands; coverage and recoverable omissions; exact source-recovery command when source was requested with a graph projection; explicit ambiguity failure with exact rerun commands",
    "evidenceCeiling": "Typed edges only to each registered provider ceiling within the explicitly selected projection and reported coverage.",
    "nonClaim": "The projection does not infer which relationships are relevant to the user task. Reference, dependency, data, state, temporal, contract, and identity edges do not become execution claims.",
    "outputCost": "bounded",
    "contrasts": [
      "refs: refs enumerates direct reference sites; evidence traverses explicitly selected typed relationships.",
      "call-graph: call-graph specializes in static calls; evidence can combine execution with other selected families.",
      "value-flow: value-flow specializes in proved transfers; evidence projects bounded dataflow alongside other families.",
      "dependence-slice: dependence-slice computes a program-dependence slice; evidence performs bounded graph projection."
    ],
    "gapClosingCommands": [
      "inspect",
      "code"
    ]
  },
  {
    "stage": "read",
    "id": "inspect",
    "command": "inspect",
    "question": "Which related source units across several known text, symbol, or location anchors should be read together?",
    "requiredInput": "One or more exact text, symbol, or file:line selectors naming the unresolved behavior.",
    "returnedFact": "one ranked, deduplicated semantic packet plus exact selector cardinality and explicit expansion coverage",
    "evidenceCeiling": "Complete current source for every materialized syntax unit; bounded selector and packet coverage remain explicit.",
    "nonClaim": "A source packet does not choose which implementation details are relevant to the user task. A reference mention does not establish executable reachability.",
    "outputCost": "potentially-large",
    "contrasts": [
      "code: inspect batches bounded behavior or source gaps; code materializes complete exact source.",
      "evidence: inspect reads implementation units; evidence projects typed relationships without source."
    ],
    "gapClosingCommands": []
  },
  {
    "stage": "read",
    "id": "code",
    "command": "code <selectors...>",
    "question": "What exact source defines these symbols, ranges, or file surfaces?",
    "requiredInput": "One or more exact symbols, file:line ranges, or file paths.",
    "returnedFact": "per-selector resolution, complete definition source, exact ranges with statically attributed same-file call closure, file export surfaces, omitted-local ledgers, and line ranges",
    "evidenceCeiling": "Exact current source bytes for every resolved selector, with omitted file-local constructs disclosed.",
    "nonClaim": "Source materialization does not establish callers, runtime reachability, or task relevance by itself.",
    "outputCost": "potentially-large",
    "contrasts": [
      "inspect: code materializes complete exact source; inspect batches bounded behavior or source gaps.",
      "outline: code reads selected implementations; outline enumerates file structure without reading every body."
    ],
    "gapClosingCommands": []
  }
] as const;
