// Generated by scripts/render-command-reference.ts. Do not edit by hand.
export const GENERATED_AGENT_COMMAND_CATALOG = [
  '- Locate control `scip-query search <exact-text>`: Where does this exact text occur in current project text, and which aligned compiler symbol owns each line? Input: One exact text literal or deliberately bounded regular expression. Returns: exact cardinality, bounded identities and source, and scope commands that recover withheld matches Ceiling: Exact current-text cardinality and locations within reported text coverage; compiler ownership only where aligned. Does not establish: Structural source ranking orders exact matches but does not establish task relevance. A literal co-occurrence does not establish a graph relationship. Cost: small. Contrast: outline: search locates exact text across files; outline enumerates compiler-owned constructs in one known file.. Close disclosed gaps with: evidence, inspect, code.',
  '- Locate control `scip-query outline <file>`: What symbols and nesting exist in this file? Input: One exact current project file path. Returns: symbol names, nesting, and line ranges Ceiling: Exact compiler-owned constructs and ranges when the file is indexed; no invented semantic overlay. Does not establish: File ownership and nesting do not establish execution or task relevance. Cost: small. Contrast: search: outline enumerates constructs in one known file; search locates exact text across current project text. code: outline returns identities and ranges; code materializes exact source for selected identities.. Close disclosed gaps with: evidence, inspect, code.',
  '- Locate control `scip-query entrypoints [text]`: Which detected external roots or entry-surface candidates match this text? Input: Optional exact text to filter candidates; otherwise the current indexed repository. Returns: entry symbols with files, confidence, evidence, and indexed caller counts Ceiling: Source/compiler-grounded entry evidence and indexed caller counts; exported-only candidates remain candidates. Does not establish: A package-public export or zero indexed callers is an entry candidate, not proof of runtime ingress. Entry classification does not establish that the callable executes. Cost: bounded. Contrast: entry-map: entrypoints locates possible external roots; entry-map traverses static calls from one selected root. search: entrypoints classifies callable roots; search only locates exact text and ownership.. Close disclosed gaps with: evidence, inspect, code.',
  '- Project control `scip-query evidence`: Which exact execution, runtime, data, state, temporal, contract, identity, ownership, or dependency relationships surround these referents? Which related source must be read only when graph evidence leaves a named implementation gap? Input: One or more exact symbol, file:line, or literal roots plus explicit family, direction, depth, and output bound. Returns: batched exact selectors and typed graph relationships; compact endpoints with exact locations and follow-up commands; coverage and recoverable omissions; exact source-recovery command when source was requested with a graph projection; explicit ambiguity failure with exact rerun commands Ceiling: Typed edges only to each registered provider ceiling within the explicitly selected projection and reported coverage. Does not establish: The projection does not infer which relationships are relevant to the user task. Reference, dependency, data, state, temporal, contract, and identity edges do not become execution claims. Cost: bounded. Contrast: refs: refs enumerates direct reference sites; evidence traverses explicitly selected typed relationships. call-graph: call-graph specializes in static calls; evidence can combine execution with other selected families. value-flow: value-flow specializes in proved transfers; evidence projects bounded dataflow alongside other families. dependence-slice: dependence-slice computes a program-dependence slice; evidence performs bounded graph projection.. Close disclosed gaps with: inspect, code.',
  '- Read control `scip-query inspect`: Which related source units across several known text, symbol, or location anchors should be read together? Input: One or more exact text, symbol, or file:line selectors naming the unresolved behavior. Returns: one ranked, deduplicated semantic packet plus exact selector cardinality and explicit expansion coverage Ceiling: Complete current source for every materialized syntax unit; bounded selector and packet coverage remain explicit. Does not establish: A source packet does not choose which implementation details are relevant to the user task. A reference mention does not establish executable reachability. Cost: potentially-large. Contrast: code: inspect batches bounded behavior or source gaps; code materializes complete exact source. evidence: inspect reads implementation units; evidence projects typed relationships without source.. Close disclosed gaps with: none.',
  '- Read control `scip-query code <selectors...>`: What exact source defines these symbols, ranges, or file surfaces? Input: One or more exact symbols, file:line ranges, or file paths. Returns: per-selector resolution, complete definition source, exact ranges with statically attributed same-file call closure, file export surfaces, omitted-local ledgers, and line ranges Ceiling: Exact current source bytes for every resolved selector, with omitted file-local constructs disclosed. Does not establish: Source materialization does not establish callers, runtime reachability, or task relevance by itself. Cost: potentially-large. Contrast: inspect: code materializes complete exact source; inspect batches bounded behavior or source gaps. outline: code reads selected implementations; outline enumerates file structure without reading every body.. Close disclosed gaps with: none.',
  '- Relationship controls: `execution incoming` — Who can call or reach this?; `execution outgoing` — What can this call or reach?; `dataflow incoming` — Where can this value come from?; `dataflow outgoing` — Where can this value go?; `runtime both` — Which producer and consumer rendezvous?; `state both` — What resource is observed or changed?; `temporal both` — What occurs before or after this?; `contract both` — What interface constrains this?; `identity both` — Are these observations the same entity?; `ownership both` — What contains or owns this?; `dependencies outgoing` — What does this statically rely on?. Choose these explicitly; the CLI does not infer them from English intent.',
  "- Evidence strengths: `exact`: Direct compiler or source evidence establishes this relationship within the provider's reported coverage. `derived`: A deterministic analysis computed this relationship from reported input facts; it was not directly observed. `candidate`: Ambiguous or heuristic evidence identifies a lead that requires exact graph or source confirmation. `mixed`: The relationship combines evidence of different strengths; its constituent methods and strengths remain disclosed. `unknown`: The relationship has no calibrated evidence strength and cannot support a stronger claim than its raw observation.",
] as const;

export const GENERATED_EXPLORATION_CONTROLS = [
  {
    stage: 'locate',
    id: 'search',
    command: 'search <exact-text>',
    question:
      'Where does this exact text occur in current project text, and which aligned compiler symbol owns each line?',
    requiredInput: 'One exact text literal or deliberately bounded regular expression.',
    returnedFact: 'exact cardinality, bounded identities and source, and scope commands that recover withheld matches',
    evidenceCeiling:
      'Exact current-text cardinality and locations within reported text coverage; compiler ownership only where aligned.',
    nonClaim:
      'Structural source ranking orders exact matches but does not establish task relevance. A literal co-occurrence does not establish a graph relationship.',
    outputCost: 'small',
    contrasts: [
      'outline: search locates exact text across files; outline enumerates compiler-owned constructs in one known file.',
    ],
    gapClosingCommands: ['evidence', 'inspect', 'code'],
  },
  {
    stage: 'locate',
    id: 'outline',
    command: 'outline <file>',
    question: 'What symbols and nesting exist in this file?',
    requiredInput: 'One exact current project file path.',
    returnedFact: 'symbol names, nesting, and line ranges',
    evidenceCeiling:
      'Exact compiler-owned constructs and ranges when the file is indexed; no invented semantic overlay.',
    nonClaim: 'File ownership and nesting do not establish execution or task relevance.',
    outputCost: 'small',
    contrasts: [
      'search: outline enumerates constructs in one known file; search locates exact text across current project text.',
      'code: outline returns identities and ranges; code materializes exact source for selected identities.',
    ],
    gapClosingCommands: ['evidence', 'inspect', 'code'],
  },
  {
    stage: 'locate',
    id: 'entrypoints',
    command: 'entrypoints [text]',
    question: 'Which detected external roots or entry-surface candidates match this text?',
    requiredInput: 'Optional exact text to filter candidates; otherwise the current indexed repository.',
    returnedFact: 'entry symbols with files, confidence, evidence, and indexed caller counts',
    evidenceCeiling:
      'Source/compiler-grounded entry evidence and indexed caller counts; exported-only candidates remain candidates.',
    nonClaim:
      'A package-public export or zero indexed callers is an entry candidate, not proof of runtime ingress. Entry classification does not establish that the callable executes.',
    outputCost: 'bounded',
    contrasts: [
      'entry-map: entrypoints locates possible external roots; entry-map traverses static calls from one selected root.',
      'search: entrypoints classifies callable roots; search only locates exact text and ownership.',
    ],
    gapClosingCommands: ['evidence', 'inspect', 'code'],
  },
  {
    stage: 'project',
    id: 'evidence',
    command: 'evidence',
    question:
      'Which exact execution, runtime, data, state, temporal, contract, identity, ownership, or dependency relationships surround these referents? Which related source must be read only when graph evidence leaves a named implementation gap?',
    requiredInput:
      'One or more exact symbol, file:line, or literal roots plus explicit family, direction, depth, and output bound.',
    returnedFact:
      'batched exact selectors and typed graph relationships; compact endpoints with exact locations and follow-up commands; coverage and recoverable omissions; exact source-recovery command when source was requested with a graph projection; explicit ambiguity failure with exact rerun commands',
    evidenceCeiling:
      'Typed edges only to each registered provider ceiling within the explicitly selected projection and reported coverage.',
    nonClaim:
      'The projection does not infer which relationships are relevant to the user task. Reference, dependency, data, state, temporal, contract, and identity edges do not become execution claims.',
    outputCost: 'bounded',
    contrasts: [
      'refs: refs enumerates direct reference sites; evidence traverses explicitly selected typed relationships.',
      'call-graph: call-graph specializes in static calls; evidence can combine execution with other selected families.',
      'value-flow: value-flow specializes in proved transfers; evidence projects bounded dataflow alongside other families.',
      'dependence-slice: dependence-slice computes a program-dependence slice; evidence performs bounded graph projection.',
    ],
    gapClosingCommands: ['inspect', 'code'],
  },
  {
    stage: 'read',
    id: 'inspect',
    command: 'inspect',
    question:
      'Which related source units across several known text, symbol, or location anchors should be read together?',
    requiredInput: 'One or more exact text, symbol, or file:line selectors naming the unresolved behavior.',
    returnedFact:
      'one ranked, deduplicated semantic packet plus exact selector cardinality and explicit expansion coverage',
    evidenceCeiling:
      'Complete current source for every materialized syntax unit; bounded selector and packet coverage remain explicit.',
    nonClaim:
      'A source packet does not choose which implementation details are relevant to the user task. A reference mention does not establish executable reachability.',
    outputCost: 'potentially-large',
    contrasts: [
      'code: inspect batches bounded behavior or source gaps; code materializes complete exact source.',
      'evidence: inspect reads implementation units; evidence projects typed relationships without source.',
    ],
    gapClosingCommands: [],
  },
  {
    stage: 'read',
    id: 'code',
    command: 'code <selectors...>',
    question: 'What exact source defines these symbols, ranges, or file surfaces?',
    requiredInput: 'One or more exact symbols, file:line ranges, or file paths.',
    returnedFact:
      'per-selector resolution, complete definition source, exact ranges with statically attributed same-file call closure, file export surfaces, omitted-local ledgers, and line ranges',
    evidenceCeiling:
      'Exact current source bytes for every resolved selector, with omitted file-local constructs disclosed.',
    nonClaim: 'Source materialization does not establish callers, runtime reachability, or task relevance by itself.',
    outputCost: 'potentially-large',
    contrasts: [
      'inspect: code materializes complete exact source; inspect batches bounded behavior or source gaps.',
      'outline: code reads selected implementations; outline enumerates file structure without reading every body.',
    ],
    gapClosingCommands: [],
  },
] as const;
