export { resolveIndexStoragePaths } from '../platform/cache-layout.js';
export { loadProjectConfig, initProjectConfig } from './config.js';
export { Watcher, createReindexRunner, resolveReindexWorkerLaunch } from './watch.js';
export type {
  ReindexCancellationResult,
  ReindexDiagnostics,
  ReindexOperation,
  ReindexRunner,
  ReindexRunnerOptions,
  ReindexRunRequest,
  ReindexWorkerLaunch,
  WatchClock,
  WatcherOptions,
  WatcherStopResult,
  WatchSubscription,
  WatchSubscriptionFactory,
  WatchSubscriptionOptions,
} from './watch.js';
export { installSkills } from './setup.js';
export { isScipInstalled, getScipVersion, printScipInstallInstructions } from '../platform/scip-cli.js';
export {
  CLI_ANALYSIS_MANIFEST_SCHEMA_VERSION,
  CLI_EVIDENCE_CONTEXT_SCHEMA_VERSION,
  CLI_JSON_ENVELOPE_KIND,
  CURRENT_CLI_JSON_ENVELOPE_SCHEMA_VERSION,
  LEGACY_CLI_JSON_ENVELOPE_SCHEMA_VERSION,
  decodeCliJsonEnvelope,
  requireCompatibleCliJsonEnvelope,
  supportedCliResultSchemaVersions,
} from './cli-json-envelope.js';
export {
  CLAIM_ACTION_PERMISSIONS,
  CLAIM_ACTION_POLICY_VERSION,
  CLAIM_COVERAGE_STATES,
  CLAIM_ORIGINS,
  CLAIM_QUALIFICATION_SCHEMA_VERSION,
  DEFAULT_REPOSITORY_POLICY_ACTION,
  PRODUCER_VALIDATION_STATUSES,
  deriveClaimCoverage,
  deriveClaimQualification,
  evaluateClaimQualification,
  isClaimQualificationV1,
} from './claim-qualification.js';
export type {
  ClaimActionPermission,
  ClaimCoverage,
  ClaimCoverageInput,
  ClaimCoverageState,
  ClaimFamilyContract,
  ClaimFamilyOriginBinding,
  ClaimOrigin,
  ClaimQualificationEvaluation,
  ClaimQualificationPredicate,
  ClaimQualificationPredicateResult,
  ClaimQualificationRequirements,
  ClaimQualificationV1,
  CommandClaimContract,
  DeriveClaimQualificationInput,
  ProducerValidation,
  ProducerValidationStatus,
  RepositoryPolicyAction,
} from './claim-qualification.js';
export {
  COMMAND_OPERATION_ROLES,
  commandOperation,
  commandOperationRoles,
  isCommandOperationRole,
  operationObservesRepository,
  resolveCommandOperationRole,
} from './command-operation.js';
export type {
  CommandOperationInvocation,
  CommandOperationRole,
  CommandOperationRule,
  CommandOperationRuleCondition,
  CommandOperationSelector,
} from './command-operation.js';
export {
  LEGACY_OBSERVATION_RECEIPT_SCHEMA_VERSION,
  OBSERVATION_IDENTITY_CANONICALIZATION_VERSION,
  OBSERVATION_IDENTITY_HASH_ALGORITHM,
  OBSERVATION_IDENTITY_SCHEMA_VERSION,
  OBSERVATION_RECEIPT_SCHEMA_VERSION,
  OBSERVATION_STATE_AUTHORITY_POLICY_VERSION,
  compareObservationReceipts,
  createObservationIdentity,
  decodeObservationReceipt,
  deriveObservationStateAuthority,
  isObservationReceipt,
  observationReceiptGenerationIdentity,
  observationReceiptStabilityLabel,
  observationReceiptWorkspaceIdentity,
} from './observation-receipt.js';
export type {
  DecodedObservationReceipt,
  DerivedObservationStateAuthority,
  ObservationAuthorityKind,
  ObservationComparedFact,
  ObservationComparisonReason,
  ObservationIdentity,
  ObservationReceipt,
  ObservationReceiptComparison,
  ObservationReceiptV1,
  ObservationReceiptV2,
  ObservationRelationshipJudgment,
  ObservationRelationshipState,
  ObservationSourceFact,
  ObservationSourceKind,
  ObservationStabilityProof,
  ObservationStabilityProofKind,
  ObservationStateAuthority,
  RelevantInputIdentity,
  RelevantInputRelationshipJudgment,
} from './observation-receipt.js';
export type {
  CliAnalysisManifestV1,
  CliEvidenceContextV1,
  CliJsonEnvelopeV1,
  CliJsonProducer,
  CompatibleCliJsonEnvelope,
  DecodedCliJsonEnvelope,
  LegacyCliJsonEnvelope,
} from './cli-json-envelope.js';
