import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { cliVersion } from './cli-support.js';

export interface SetupCiResult {
  path: string;
  written: boolean;
  skipped: boolean;
  content: string;
  reason?: string;
}

export function setupCiWorkflow(projectRoot: string, opts: { force?: boolean; dryRun?: boolean } = {}): SetupCiResult {
  const path = join(projectRoot, '.github', 'workflows', 'scip-query.yml');
  const content = renderScipQueryWorkflow({ hasNpmProject: existsSync(join(projectRoot, 'package.json')) });
  if (existsSync(path) && !opts.force) {
    return {
      path,
      written: false,
      skipped: true,
      content,
      reason: 'Workflow already exists. Re-run with --force to overwrite.',
    };
  }
  if (!opts.dryRun) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
  return { path, written: !opts.dryRun, skipped: false, content };
}

function renderScipQueryWorkflow(opts: { hasNpmProject: boolean }): string {
  const packageSpecifier = `scip-query@${cliVersion}`;
  const installStep = opts.hasNpmProject
    ? '      - run: npm ci\n'
    : [
        "      # TODO: install this repository's dependencies before indexing.",
        '      # This project did not have a package.json when the workflow was generated.',
      ].join('\n') + '\n';
  return `name: scip-query

# Generated by scip-query setup-ci.
# Install the language indexers your repository needs before the reindex step
# if they are not already provided by your dependency install.

on:
  pull_request:

jobs:
  diff-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/cache@v4
        with:
          path: ~/.cache/scip-query
          key: scip-query-\${{ runner.os }}-\${{ hashFiles('package-lock.json', 'pnpm-lock.yaml', 'yarn.lock', 'bun.lockb', 'Cargo.lock', 'go.sum', 'poetry.lock', 'uv.lock') }}
${installStep}      - run: npx ${packageSpecifier} reindex
      - run: npx ${packageSpecifier} diff-gate --base "origin/\${{ github.base_ref }}"
`;
}
