export { stats } from './stats.js';
export { files } from './files.js';
export { symbols } from './symbols.js';
export { methods } from './methods.js';
export { refs } from './refs.js';
export { trace } from './trace.js';
export { deps, rdeps } from './deps.js';
export { system } from './system.js';
export { surface } from './surface.js';
export { dead } from './dead.js';
export { hotspots } from './hotspots.js';
export { imports, importedBy, unusedImports } from './imports.js';
export { outline } from './outline.js';
export { members } from './members.js';
export { fanIn, fanOut, topFanIn, topFanOut } from './fan.js';
export { coupling, topCoupling } from './coupling.js';
export { cycles } from './cycles.js';
export { bottlenecks } from './bottlenecks.js';
export { isolated } from './isolated.js';
export { byKind, kindCounts } from './by-kind.js';
export { deepChains } from './deep-chains.js';
export { hierarchy } from './hierarchy.js';
export { callGraph } from './call-graph.js';
export { similar, similarAll } from './similar.js';
export { similarFiles } from './similar-files.js';
export { similarChains } from './similar-chains.js';
export { extractCandidates } from './extract-candidates.js';
export { affected } from './affected.js';
export { changeSurface } from './change-surface.js';
export { cleanupPlan } from './cleanup-plan.js';
export { diffGate } from './diff-gate.js';
export { incompleteMigration } from './incomplete-migration.js';
export { coChange } from './co-change.js';
export { docDrift } from './doc-drift.js';
export { recentDuplicates } from './recent-duplicates.js';
export { planContext } from './plan-context.js';
export { checkHealthBaseline, collectBaselineFindings, writeHealthBaseline } from './health-baseline.js';
export {
  diffImpact,
  diffImpactPartial,
  diffImpactPlan,
  mergeDiffImpactPartials,
} from './diff-impact.js';
export { drift } from './drift.js';
export { wrapperCandidates } from './wrapper-candidates.js';
export { passthroughCandidates } from './passthrough-candidates.js';
export { staleAbstractions } from './stale-abstractions.js';
export { unusedParams } from './unused-params.js';
export { complexityHotspots } from './complexity-hotspots.js';
export { HEALTH_PHASES, health, healthPhase, healthReportFromPhases } from './health.js';
export { convergence } from './convergence.js';
export { code } from './code.js';
export { complexity } from './complexity.js';
export { dataflow } from './dataflow.js';
export { slice } from './slice.js';
export { redundantReexports } from './redundant-reexports.js';
export { selfAudit } from './self-audit.js';
export { similarSignatures } from './similar-signatures.js';

export type { StatsResult } from './stats.js';
export type { FileResult } from './files.js';
export type { SymbolResult } from './symbols.js';
export type { MethodResult } from './methods.js';
export type { RefResult } from './refs.js';
export type { DepResult } from './deps.js';
export type { TraceResult } from './trace.js';
export type { SystemResult } from './system.js';
export type { SurfaceResult } from './surface.js';
export type { DeadSymbolResult, DeadSummary } from './dead.js';
export type { HotspotResult } from './hotspots.js';
export type { ImportResult, UnusedImportResult } from './imports.js';
export type { OutlineNode } from './outline.js';
export type { MemberResult } from './members.js';
export type { FanResult } from './fan.js';
export type { CouplingResult } from './coupling.js';
export type { CycleResult } from './cycles.js';
export type { BottleneckResult } from './bottlenecks.js';
export type { IsolatedResult } from './isolated.js';
export type { ByKindResult } from './by-kind.js';
export type { DeepChainResult } from './deep-chains.js';
export type { HierarchyNode } from './hierarchy.js';
export type { CallGraphResult } from './call-graph.js';
export type { DriftResult, DriftSummary } from './drift.js';
export type { WrapperCandidate } from './wrapper-candidates.js';
export type { PassthroughCandidate } from './passthrough-candidates.js';
export type { StaleAbstraction } from './stale-abstractions.js';
export type { UnusedParamsFinding } from './unused-params.js';
export type { ComplexityHotspot } from './complexity-hotspots.js';
export type { SimilarSymbolResult } from './similar.js';
export type { SimilarFileResult } from './similar-files.js';
export type { SimilarChainResult } from './similar-chains.js';
export type { ExtractCandidate } from './extract-candidates.js';
export type { HealthAction, HealthReport } from './health-report.js';
export type { ConvergenceResult } from './convergence.js';
export type { CodeResult } from './code.js';
export type { ComplexityResult } from './complexity.js';
export type { DataflowResult } from './dataflow.js';
export type { SliceResult } from './slice.js';
export type { AffectedResult } from './affected.js';
export type { ChangeSurfaceEntry, ChangeSurfaceResult } from './change-surface.js';
export type { CleanupBatch, CleanupPlanEntry, CleanupPlanResult } from './cleanup-plan.js';
export type { DiffGateCheck, DiffGateFinding, DiffGateResult } from './diff-gate.js';
export type { CoChangeFinding, CoChangeResult } from './co-change.js';
export type { DocDriftFinding, DocDriftResult, DocDriftSubject } from './doc-drift.js';
export type { RecentDuplicateFinding, RecentDuplicatesResult } from './recent-duplicates.js';
export type { BaselineComparison, HealthBaselineFile } from './health-baseline.js';
export type { PlanContextOptions, PlanContextResult } from './plan-context.js';
export type { DiffImpactResult } from './diff-impact.js';
export type { RedundantReexport } from './redundant-reexports.js';
export type { AuditDisagreement, AuditQuestionScore, SelfAuditResult } from './self-audit.js';
export type { SimilarSignatureGroup } from './similar-signatures.js';
