/**
 * Single source of truth for the published query surface.
 *
 * One name list drives all three published-surface artifacts that previously
 * had to be hand-synchronized: the tsup build entries (tsup.config.ts), the
 * package.json `./queries/*` subpath exports, and the contract test that
 * checks them (tests/cli-contract.test.ts).
 *
 * Query source paths are intentionally separate from published names. The
 * package contract remains `scip-query/queries/<name>` even when the source
 * implementation lives in a domain folder under src/queries/.
 */

/** Query modules published as `scip-query/queries/<name>` subpath exports. */
export const PUBLIC_QUERY_ENTRIES = [
  'affected',
  'architecture',
  'bottlenecks',
  'by-kind',
  'call-graph',
  'change-surface',
  'cleanup-plan',
  'co-change',
  'code',
  'complexity',
  'complexity-hotspots',
  'convergence',
  'coupling',
  'cycles',
  'dataflow',
  'dead',
  'decorative-checkers',
  'deep-chains',
  'deps',
  'diff-impact',
  'doc-drift',
  'duplicate-bodies',
  'drift',
  'evidence',
  'extract-candidates',
  'fan',
  'files',
  'health',
  'hierarchy',
  'hotspots',
  'imports',
  'unused-imports',
  'incomplete-migration',
  'index',
  'isolated',
  'locality-candidates',
  'members',
  'methods',
  'not-implemented',
  'outline',
  'passthrough-candidates',
  'context',
  'react-component-duplicates',
  'react-hook-candidates',
  'react-large-component-pressure',
  'recent-duplicates',
  'redundant-reexports',
  'refs',
  'self-audit',
  'similar',
  'similar-chains',
  'similar-files',
  'similar-signatures',
  'slice',
  'source-inspection',
  'source-search',
  'stale-abstractions',
  'stats',
  'surface',
  'symbols',
  'system',
  'test-quality',
  'trace',
  'twin-ab',
  'twin-drift',
  'unused-params',
  'vue-composable-candidates',
  'vue-component-duplicates',
  'vue-large-view-pressure',
  'wrapper-candidates',
] as const;

export type PublicQueryEntry = (typeof PUBLIC_QUERY_ENTRIES)[number];

export const PUBLIC_QUERY_SOURCE_PATHS = {
  affected: 'src/queries/graph/affected.ts',
  architecture: 'src/queries/graph/architecture.ts',
  bottlenecks: 'src/queries/graph/bottlenecks.ts',
  'by-kind': 'src/queries/navigation/by-kind.ts',
  'call-graph': 'src/queries/navigation/call-graph.ts',
  'change-surface': 'src/queries/impact/change-surface.ts',
  'cleanup-plan': 'src/queries/cleanup/cleanup-plan.ts',
  'co-change': 'src/queries/cleanup/co-change.ts',
  code: 'src/queries/navigation/code.ts',
  complexity: 'src/queries/quality/complexity.ts',
  'complexity-hotspots': 'src/queries/quality/complexity-hotspots.ts',
  convergence: 'src/queries/cleanup/convergence.ts',
  coupling: 'src/queries/graph/coupling.ts',
  cycles: 'src/queries/graph/cycles.ts',
  dataflow: 'src/queries/navigation/dataflow.ts',
  dead: 'src/queries/cleanup/dead.ts',
  'decorative-checkers': 'src/queries/cleanup/decorative-checkers.ts',
  'deep-chains': 'src/queries/graph/deep-chains.ts',
  deps: 'src/queries/navigation/deps.ts',
  'diff-impact': 'src/queries/impact/diff-impact.ts',
  'doc-drift': 'src/queries/cleanup/doc-drift.ts',
  'duplicate-bodies': 'src/queries/cleanup/duplicate-bodies.ts',
  drift: 'src/queries/cleanup/drift.ts',
  evidence: 'src/queries/navigation/evidence.ts',
  'extract-candidates': 'src/queries/cleanup/extract-candidates.ts',
  fan: 'src/queries/graph/fan.ts',
  files: 'src/queries/navigation/files.ts',
  health: 'src/queries/health/health.ts',
  hierarchy: 'src/queries/navigation/hierarchy.ts',
  hotspots: 'src/queries/graph/hotspots.ts',
  imports: 'src/queries/navigation/imports.ts',
  'unused-imports': 'src/queries/navigation/imports.ts',
  'incomplete-migration': 'src/queries/impact/incomplete-migration.ts',
  index: 'src/queries/index.ts',
  isolated: 'src/queries/cleanup/isolated.ts',
  'locality-candidates': 'src/queries/cleanup/locality-candidates.ts',
  members: 'src/queries/navigation/members.ts',
  methods: 'src/queries/navigation/methods.ts',
  'not-implemented': 'src/queries/cleanup/not-implemented.ts',
  outline: 'src/queries/navigation/outline.ts',
  'passthrough-candidates': 'src/queries/cleanup/passthrough-candidates.ts',
  context: 'src/queries/impact/context.ts',
  'react-component-duplicates': 'src/queries/frontend/react-component-duplicates.ts',
  'react-hook-candidates': 'src/queries/frontend/react-hook-candidates.ts',
  'react-large-component-pressure': 'src/queries/frontend/react-large-component-pressure.ts',
  'recent-duplicates': 'src/queries/cleanup/recent-duplicates.ts',
  'redundant-reexports': 'src/queries/cleanup/redundant-reexports.ts',
  refs: 'src/queries/navigation/refs.ts',
  'self-audit': 'src/queries/quality/self-audit.ts',
  similar: 'src/queries/cleanup/similar.ts',
  'similar-chains': 'src/queries/cleanup/similar-chains.ts',
  'similar-files': 'src/queries/cleanup/similar-files.ts',
  'similar-signatures': 'src/queries/cleanup/similar-signatures.ts',
  slice: 'src/queries/navigation/slice.ts',
  'source-inspection': 'src/queries/navigation/source-inspection.ts',
  'source-search': 'src/queries/navigation/source-search.ts',
  'stale-abstractions': 'src/queries/cleanup/stale-abstractions.ts',
  stats: 'src/queries/navigation/stats.ts',
  surface: 'src/queries/navigation/surface.ts',
  symbols: 'src/queries/navigation/symbols.ts',
  system: 'src/queries/navigation/system.ts',
  'test-quality': 'src/queries/cleanup/test-quality.ts',
  trace: 'src/queries/navigation/trace.ts',
  'twin-ab': 'src/queries/cleanup/twin-ab.ts',
  'twin-drift': 'src/queries/cleanup/twin-drift.ts',
  'unused-params': 'src/queries/cleanup/unused-params.ts',
  'vue-composable-candidates': 'src/queries/frontend/vue-composable-candidates.ts',
  'vue-component-duplicates': 'src/queries/frontend/vue-component-duplicates.ts',
  'vue-large-view-pressure': 'src/queries/frontend/vue-large-view-pressure.ts',
  'wrapper-candidates': 'src/queries/cleanup/wrapper-candidates.ts',
} as const satisfies Record<PublicQueryEntry, string>;
