/**
 * Generated by 'scip-query tla instrument'. Dependency-free trace recorder.
 *
 * Usage inside a mapped action (record the model-visible slice around the
 * mutation):
 *
 *   import { tlaRecord } from './scip-tla-recorder.js';
 *   export function enqueue(job: string) {
 *     const before = snapshot();
 *     queue.push(job);
 *     tlaRecord('Enqueue', before, snapshot());
 *   }
 *
 * where snapshot() projects the mapped variables to JSON scalars — fill in
 * each field with the real runtime value, e.g.
 *   const snapshot = () => ({ stage: undefined, planState: undefined, checksRan: undefined, findingsState: undefined, allSkipped: undefined, exitState: undefined }); // fill in each field
 *
 * Recording is enabled only when SCIP_TLA_TRACE names an output path, so the
 * wiring is safe to leave in place. The output is a JSON array compatible
 * with 'scip-query tla trace-check --trace <path>'.
 */
import { readFileSync, writeFileSync } from 'node:fs';

interface TlaTraceStep {
  action: string;
  before: Record<string, unknown>;
  after: Record<string, unknown>;
}

const tracePath = process.env['SCIP_TLA_TRACE'];

export function tlaRecord(action: string, before: Record<string, unknown>, after: Record<string, unknown>): void {
  if (!tracePath) return;
  let steps: TlaTraceStep[] = [];
  try {
    steps = JSON.parse(readFileSync(tracePath, 'utf8')) as TlaTraceStep[];
    if (!Array.isArray(steps)) steps = [];
  } catch {
    steps = [];
  }
  steps.push({ action, before, after });
  writeFileSync(tracePath, JSON.stringify(steps, null, 2));
}
