import type { ScipDatabase } from '../storage/db.js';
import { findFirstSymbolMatch } from '../symbols/symbol-lookup.js';
import type { TlaModelContract } from './model-contract.js';

/**
 * TLA P2 (`tla instrument`): generate a dependency-free trace recorder plus a
 * wiring guide derived from the mapping contract. Instrumentation is
 * assisted, not automatic — the agent wires `record(...)` into each mapped
 * action's implementation (usually 1 line per action), runs the existing
 * tests, and feeds the recorded trace to `tla trace-check`.
 */

export interface InstrumentWiringSite {
  action: string;
  codeRef: string;
  file: string | null;
  line: number | null;
  writes: string[];
}

export interface TlaInstrumentResult {
  recorderSource: string;
  wiring: InstrumentWiringSite[];
  variables: string[];
}

export function buildInstrumentation(db: ScipDatabase, contract: TlaModelContract): TlaInstrumentResult {
  const variables = Object.keys(contract.variables);
  const wiring: InstrumentWiringSite[] = Object.entries(contract.actions).map(([action, mapping]) => {
    const ref = mapping.code[0] ?? '';
    const match = ref ? findFirstSymbolMatch(db, ref) : null;
    return {
      action,
      codeRef: ref,
      file: match?.relativePath ?? null,
      line: match ? match.startLine + 1 : null,
      writes: mapping.writes,
    };
  });
  return { recorderSource: renderRecorder(variables), wiring, variables };
}

function renderRecorder(variables: readonly string[]): string {
  return `/**
 * Generated by 'scip-query tla instrument'. Dependency-free trace recorder.
 *
 * Usage inside a mapped action (record the model-visible slice around the
 * mutation):
 *
 *   import { tlaRecord } from './scip-tla-recorder.js';
 *   export function enqueue(job: string) {
 *     const before = snapshot();
 *     queue.push(job);
 *     tlaRecord('Enqueue', before, snapshot());
 *   }
 *
 * where snapshot() projects the mapped variables to JSON scalars — fill in
 * each field with the real runtime value, e.g.
 *   const snapshot = () => ({ ${variables.map((name) => `${name}: undefined`).join(', ')} }); // fill in each field
 *
 * Recording is enabled only when SCIP_TLA_TRACE names an output path, so the
 * wiring is safe to leave in place. The output is a JSON array compatible
 * with 'scip-query tla trace-check --trace <path>'.
 */
import { readFileSync, writeFileSync } from 'node:fs';

interface TlaTraceStep {
  action: string;
  before: Record<string, unknown>;
  after: Record<string, unknown>;
}

const tracePath = process.env['SCIP_TLA_TRACE'];

export function tlaRecord(action: string, before: Record<string, unknown>, after: Record<string, unknown>): void {
  if (!tracePath) return;
  let steps: TlaTraceStep[] = [];
  try {
    steps = JSON.parse(readFileSync(tracePath, 'utf8')) as TlaTraceStep[];
    if (!Array.isArray(steps)) steps = [];
  } catch {
    steps = [];
  }
  steps.push({ action, before, after });
  writeFileSync(tracePath, JSON.stringify(steps, null, 2));
}
`;
}
