import * as queries from '../../../queries/index.js';
import type { CommandDescriptor } from '../../command-kit/command-descriptor-types.js';
import { commandOperation } from '../../command-operation.js';
import { definedLimitOption, stringOptionValue } from '../../command-kit/command-execution.js';
import {
  analysisAgentContract,
  doc,
  option,
  parseInteger,
  parseNumber,
  parsePositiveInteger,
  withJsonOption,
} from '../../command-kit/command-spec-builders.js';
import { groupedQueryCommand } from '../../command-kit/query-command-builders.js';
import {
  handleCleanupPlan,
  handleDead,
  handleDecorativeCheckers,
  handleDocDrift,
  handleDrift,
  handleDuplicateBodies,
  handleLocalityCandidates,
  handleNotImplemented,
  handlePassthroughCandidates,
  handleRecentDuplicates,
  handleSimilar,
  handleSimilarFiles,
  handleSimilarSignatures,
  handleSliceCohesion,
  handleTestQuality,
  handleTwinDrift,
  handleUnusedImports,
  handleUnusedParams,
} from './handlers.js';
import {
  handleReactComponentDuplicates,
  handleReactHookCandidates,
  handleReactLargeComponentPressure,
  handleVueComponentDuplicates,
  handleVueComposableCandidates,
  handleVueLargeViewPressure,
} from './frontend-handlers.js';

type CleanupCommandDescriptor = Omit<CommandDescriptor, 'docs'> & {
  docs?: CommandDescriptor['docs'];
};

type HeuristicCleanupCommandDescriptor = Omit<CleanupCommandDescriptor, 'heuristic'> & {
  heuristicLabel: string;
};

function cleanupCommand(descriptor: CleanupCommandDescriptor): CommandDescriptor {
  return {
    docs: doc('Cleanup'),
    ...descriptor,
  };
}

function heuristicCleanupCommand({
  heuristicLabel,
  ...descriptor
}: HeuristicCleanupCommandDescriptor): CommandDescriptor {
  return cleanupCommand({
    ...descriptor,
    heuristic: { label: heuristicLabel },
  });
}

export const cleanupQueryCommandDescriptors: CommandDescriptor[] = [
  cleanupCommand({
    id: 'unused-params',
    command: 'unused-params',
    agent: analysisAgentContract(
      'Which trailing parameters are never read by their bodies?',
      'candidate parameters with callable and file identities',
      [],
      'bounded',
      'repository',
    ),
    description: 'Speculative-generality candidates: trailing parameters no body ever uses (TS/JS)',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Maximum findings', parseInteger, 30),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'unused trailing parameter candidates' },
    renderShape: 'list',
    docs: doc('Cleanup', ['scip-query unused-params -s src/services']),
    handler: handleUnusedParams,
  }),
  cleanupCommand({
    id: 'cleanup-plan',
    command: 'cleanup-plan',
    agent: analysisAgentContract(
      'Which unused-code candidates form deletion batches in dependency order?',
      'ordered cleanup batches, evidence, and optional verification outcomes',
      [],
      'bounded',
      'repository',
      commandOperation('repository-preview'),
    ),
    description: 'Ordered, batched deletion plan: graph-fact dead code plus the cascade candidates it unlocks',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Only include symbols >= N lines', parseInteger, 1),
      option('--max-depth <n>', 'Maximum cascade depth', parseInteger, 5),
      option('--verify', 'Apply batches in an isolated HEAD snapshot and run the project checker (tsc / cargo check)'),
      option('--patch', 'With --verify, print the compiler-verified deletion patch to stdout'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query cleanup-plan --min-loc 3', 'scip-query cleanup-plan --verify']),
    handler: handleCleanupPlan,
  }),
  cleanupCommand({
    id: 'recent-duplicates',
    command: 'recent-duplicates',
    agent: analysisAgentContract(
      'Which recently added files contain code similar to code in older files?',
      'recent and established symbol pairs with similarity evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      'Similarity candidates in recently added files, oriented by file age; function creation time is not known',
    options: withJsonOption([
      option('--window <n>', 'How many commits back counts as "recent"', parseInteger, 100),
      option('--min-similarity <n>', 'Minimum similarity (0-1); omitted uses detector defaults', parseNumber),
      option('-n, --limit <n>', 'Maximum findings', parseInteger, 30),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded semantic and git-history analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'recent re-implementation candidates' },
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query recent-duplicates --window 50']),
    handler: handleRecentDuplicates,
  }),
  cleanupCommand({
    id: 'doc-drift',
    command: 'doc-drift [doc]',
    agent: analysisAgentContract(
      'Which documentation may be stale relative to changing code?',
      'document paths, coupled code subjects, and history evidence',
      ['path'],
      'bounded',
      'repository',
    ),
    description: 'Stale-doc candidates: code the doc references or co-changed with kept changing after the doc stopped',
    options: withJsonOption([
      option('-n, --limit <n>', 'Maximum docs to report', parseInteger, 20),
      option('--min-coupling <n>', 'Minimum historical co-changes to track a subject', parseInteger, 3),
      option('--full', 'Run unbounded git-history analysis on large indexes'),
    ]),
    heuristic: { label: 'doc drift candidates' },
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query doc-drift', 'scip-query doc-drift AGENTS.md']),
    handler: handleDocDrift,
  }),
  cleanupCommand({
    id: 'dead',
    command: 'dead [scope]',
    agent: analysisAgentContract(
      'Which symbols have no repository use or only file-internal use?',
      'symbol identities, ranges, liveness classes, and evidence',
      ['path'],
      'bounded',
      'repository',
    ),
    description: 'Find repository-dead code, file-internal symbols, and implicit-usage signals',
    options: withJsonOption([
      option('--min-loc <n>', 'Only show symbols >= N lines', parseInteger, 1),
      option('--include-tests', 'Include definitions from test files (test references always count)'),
      option('--skip-barrels', 'Ignore refs from barrel re-export files'),
      option('--include-members', 'Include class members'),
      option('--only-dead', 'Show only [dead code] symbols (skip file-internal and implicit-usage signals)'),
      option('--only-internal', 'Show only [file-internal only] symbols (skip dead-code and implicit-usage signals)'),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query dead --min-loc 10']),
    handler: handleDead,
  }),
  cleanupCommand({
    id: 'unused-imports',
    command: 'unused-imports <file>',
    agent: analysisAgentContract(
      'Which imports in this file are unused?',
      'unused local binding candidates and their files',
      ['file'],
      'bounded',
    ),
    description: 'Find imports not referenced in the same file',
    options: withJsonOption([option('--full', 'Run unbounded semantic analysis on large indexes')]),
    budget: 'semantic',
    renderShape: 'list',
    handler: handleUnusedImports,
  }),
  heuristicCleanupCommand({
    id: 'similar',
    command: 'similar [symbol] [other]',
    agent: analysisAgentContract(
      'Which callable resembles this one, or how similar are these two?',
      'symbol pairs, similarity scores, and shared evidence',
      ['symbol', 'symbol'],
      'bounded',
      'repository',
    ),
    description: 'Find heuristic function similarity candidates from callee fingerprints',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum weighted-cosine similarity (0-1)', parseNumber, 0.4),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-callees <n>', 'Minimum callees to consider', parseInteger, 4),
      option('--cross-file-only', 'Only show cross-file pairs (skip same-file matches)'),
      option('--plan', 'Render a consolidation preview for two symbols'),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'similarity candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleSimilar,
  }),
  heuristicCleanupCommand({
    id: 'similar-files',
    command: 'similar-files [file]',
    agent: analysisAgentContract(
      'Which files reference similar sets of dependencies?',
      'file pairs with filtered dependency-set overlap; conceptual ownership requires review',
      ['file'],
      'bounded',
      'repository',
    ),
    description: 'Find heuristic similar-file candidates from dependency profiles',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum Jaccard similarity (0-1)', parseNumber, 0.5),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option(
        '--min-deps <n>',
        'Minimum dependencies after excluding globally common dependencies (default 4, or 1 with a file)',
        parseInteger,
      ),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'similar file candidates',
    renderShape: 'custom',
    handler: handleSimilarFiles,
  }),
  heuristicCleanupCommand({
    id: 'react-component-duplicates',
    command: 'react-component-duplicates [file]',
    agent: analysisAgentContract(
      'Which React components appear to duplicate one another?',
      'component pairs with structural similarity evidence',
      ['file'],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic duplicated React component structure candidates from JSX tags, props, events, and bindings',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum JSX structure similarity (0-1)', parseNumber, 0.62),
      option('--min-tokens <n>', 'Minimum structural tokens to consider', parseInteger, 8),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'React component duplicate candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleReactComponentDuplicates,
  }),
  heuristicCleanupCommand({
    id: 'react-hook-candidates',
    command: 'react-hook-candidates [file]',
    agent: analysisAgentContract(
      'Which repeated React logic could become a custom hook?',
      'component groups and shared hook-shaped behavior',
      ['file'],
      'bounded',
      'repository',
    ),
    description: 'Find heuristic React hook extraction candidates from shared state, effects, requests, and handlers',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum behavior similarity (0-1)', parseNumber, 0.45),
      option('--min-shared-behaviors <n>', 'Minimum shared behavior tokens', parseInteger, 6),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'React hook extraction candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleReactHookCandidates,
  }),
  heuristicCleanupCommand({
    id: 'react-large-component-pressure',
    command: 'react-large-component-pressure [file]',
    agent: analysisAgentContract(
      'Which React components exceed the selected line or vocabulary thresholds?',
      'component identities, line counts, and distinct JSX/behavior token counts',
      ['file'],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic large React component pressure candidates from component lines, JSX structure, and hook behavior',
    options: withJsonOption([
      option('--min-component-lines <n>', 'Minimum component lines', parseInteger, 300),
      option('--min-file-lines <n>', 'Minimum file lines', parseInteger, 800),
      option('--min-jsx-tokens <n>', 'Minimum JSX structure tokens', parseInteger, 80),
      option('--min-behavior-tokens <n>', 'Minimum behavior tokens', parseInteger, 40),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'large React component pressure candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleReactLargeComponentPressure,
  }),
  heuristicCleanupCommand({
    id: 'vue-component-duplicates',
    command: 'vue-component-duplicates [file]',
    agent: analysisAgentContract(
      'Which Vue components appear to duplicate one another?',
      'component pairs with structural similarity evidence',
      ['file'],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic duplicated Vue component structure candidates from template tags, bindings, slots, and directives',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum template similarity (0-1)', parseNumber, 0.62),
      option('--min-tokens <n>', 'Minimum structural tokens to consider', parseInteger, 8),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'Vue component duplicate candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleVueComponentDuplicates,
  }),
  heuristicCleanupCommand({
    id: 'vue-composable-candidates',
    command: 'vue-composable-candidates [file]',
    agent: analysisAgentContract(
      'Which repeated Vue logic could become a composable?',
      'component groups and shared composable-shaped behavior',
      ['file'],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic Vue composable extraction candidates from shared state, effects, requests, and template bindings',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum behavior similarity (0-1)', parseNumber, 0.45),
      option('--min-shared-behaviors <n>', 'Minimum shared behavior tokens', parseInteger, 6),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'Vue composable extraction candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleVueComposableCandidates,
  }),
  heuristicCleanupCommand({
    id: 'vue-large-view-pressure',
    command: 'vue-large-view-pressure [file]',
    agent: analysisAgentContract(
      'Which Vue views exceed selected template, script, style, or delegated-code line thresholds?',
      'view identities and measured line counts; responsibility boundaries require review',
      ['file'],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic large Vue view pressure candidates from template, script, style, and external script line counts',
    options: withJsonOption([
      option('--min-total-lines <n>', 'Minimum component plus one-hop delegated composable lines', parseInteger, 800),
      option('--min-template-lines <n>', 'Minimum template lines', parseInteger, 300),
      option('--min-script-lines <n>', 'Minimum script lines', parseInteger, 300),
      option('--min-style-lines <n>', 'Minimum style lines', parseInteger, 500),
      option('--review-thresholds', 'Use lower review thresholds without changing health scoring'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'large Vue view pressure candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleVueLargeViewPressure,
  }),
  heuristicCleanupCommand({
    id: 'locality-candidates',
    command: 'locality-candidates [symbol-or-file]',
    agent: analysisAgentContract(
      'Which definitions live far from most of their consumers?',
      'symbols, current homes, consumer locality, and suggested homes',
      [['symbol', 'file']],
      'bounded',
      'repository',
    ),
    description: 'Find directory-locality and ancestry candidates from consumer ownership',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit scan mode to files matching path'),
      option('--min-consumers <n>', 'Minimum consumers in scan mode', parseInteger, 1),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'locality candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', [
      'scip-query locality-candidates',
      'scip-query locality-candidates formatName --json',
      'scip-query locality-candidates src/shared/date.ts',
    ]),
    handler: handleLocalityCandidates,
  }),
  heuristicCleanupCommand({
    id: 'drift',
    command: 'drift [module]',
    agent: analysisAgentContract(
      'Where has a module or abstraction drifted across parallel implementations?',
      'drifted symbol families, files, and evidence',
      ['module'],
      'bounded',
      'repository',
    ),
    description:
      'Detect drift candidates: unused imports and declared architecture violations; pass --architecture for boundary context',
    options: withJsonOption([
      option(
        '--min-deviation <n>',
        'Minimum sibling files before reporting unique dependency deviations',
        parsePositiveInteger,
        5,
      ),
      option(
        '--patterns',
        'Also include pattern-deviation findings ("only sibling importing X") — off by default: low precision at scale (21.2 calibration)',
        undefined,
        false,
      ),
      option(
        '--architecture',
        'Include boundary coverage, undeclared edges, reciprocal pairs, and connected groups',
        undefined,
        false,
      ),
      option('-n, --limit <n>', 'Number of results', parseInteger, 50),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'drift candidates',
    budget: 'semantic',
    renderShape: 'grouped-by-file',
    handler: handleDrift,
  }),
  heuristicCleanupCommand({
    id: 'passthrough-candidates',
    command: 'passthrough-candidates',
    agent: analysisAgentContract(
      'Which small callables appear to forward to a single target?',
      'callable identities, forwarding targets, and source evidence',
      [],
      'bounded',
      'repository',
    ),
    description: 'Find heuristic passthrough candidates that forward to one callee',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--max-loc <n>', 'Maximum LOC for candidates', parseInteger, 15),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'passthrough candidates',
    budget: 'candidate-scan',
    renderShape: 'list',
    handler: handlePassthroughCandidates,
  }),
  heuristicCleanupCommand({
    id: 'slice-cohesion',
    command: 'slice-cohesion [symbol]',
    agent: {
      ...analysisAgentContract(
        'Which functions compute several independent results in one body, and where are the local slices disjoint?',
        'per-function backward-slice partitions, outputs, observed input names, and analysis gaps; extraction safety requires source review',
        ['symbol'],
        'bounded',
        'repository',
      ),
      resultUnits: { kind: 'rows' },
    },
    description:
      'Find low-cohesion candidates from backward slices: outputs whose statements never meet are separate local computations',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum function LOC to scan', parseInteger, 12),
      option('--min-statements <n>', 'Minimum counted statements before a partition is reported', parseInteger, 10),
      option('--min-cluster <n>', 'Minimum statements in an extractable cluster', parseInteger, 4),
      option('-n, --limit <n>', 'Number of results to print (cannot be combined with --full)', parseInteger, 20),
      option(
        '--scan-limit <n>',
        'Maximum candidates to analyze, largest first; bounds the work, unlike --limit',
        parseInteger,
      ),
      option('--full', 'Analyze every candidate on large indexes (cannot be combined with --limit)'),
    ]),
    heuristicLabel: 'slice-cohesion candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleSliceCohesion,
  }),
  groupedQueryCommand({
    id: 'redundant-reexports',
    command: 'redundant-reexports',
    agent: analysisAgentContract(
      'Which re-export declarations have no resolved local source consumers?',
      're-export sites, original definitions, and consumer evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      'Find re-export candidates with no resolved local source imports or re-exports; external use is unknown',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded analysis on large indexes'),
    ],
    docs: doc('Cleanup'),
    query: ({ db, opts }) =>
      queries.redundantReexports(db, {
        scope: stringOptionValue(opts, 'scope'),
        limit: definedLimitOption(opts, 'limit', 30),
      }),
    format: (r) =>
      `  ${r.shortName}  (from ${r.originalFile})\n` +
      `    barrel: ${r.barrelConsumers} consumer(s) | direct: ${r.directConsumers} consumer(s) | tier: ${r.actionTier}\n` +
      `    Recommendation: ${r.recommendation}` +
      (r.surfaceEvidence.length > 0 ? `\n    Surface evidence: ${r.surfaceEvidence.join('; ')}` : ''),
    key: (r) => r.barrelFile,
    emptyMessage: () => 'No redundant re-exports found.',
    after: (rows) => console.log(`\n${rows.length} redundant re-export(s).`),
  }),
  cleanupCommand({
    id: 'duplicate-bodies',
    command: 'duplicate-bodies',
    agent: analysisAgentContract(
      'Which callable bodies are exact duplicates?',
      'callable groups with exact normalized-body identity',
      [],
      'bounded',
      'repository',
    ),
    description: 'Find exact duplicate small-body candidates across files',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--max-loc <n>', 'Maximum LOC per function body', parseInteger, 15),
      option('--min-loc <n>', 'Minimum body LOC (excludes single-statement forwarding boilerplate)', parseInteger, 3),
      option('-n, --limit <n>', 'Number of groups', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'duplicate body candidates' },
    renderShape: 'list',
    handler: handleDuplicateBodies,
  }),
  cleanupCommand({
    id: 'twin-drift',
    command: 'twin-drift',
    agent: analysisAgentContract(
      'Which similarly named functions have matching or divergent normalized bodies?',
      'function groups with name, token, and divergence evidence; shared responsibility requires review',
      [],
      'bounded',
      'repository',
    ),
    description: 'Twin drift candidates: same-name (or near-name) functions across files with diverged bodies',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option(
        '--min-similarity <n>',
        'Minimum normalized-token Jaccard similarity to report as divergent (0-1)',
        parseNumber,
        0.3,
      ),
      option('--include-homonyms', 'Also report same-name pairs below the similarity threshold (likely coincidental)'),
      option('-n, --limit <n>', 'Number of groups', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'twin drift candidates' },
    evidence: 'heuristic',
    renderShape: 'list',
    handler: handleTwinDrift,
  }),
  heuristicCleanupCommand({
    id: 'not-implemented',
    command: 'not-implemented',
    agent: analysisAgentContract(
      'Which callables are placeholders rather than real implementations?',
      'callable identities and placeholder evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      'Placeholder candidates with observed consumer or entry-surface evidence: throw-stub, TODO plus default return, or empty body',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'placeholder stub candidates',
    budget: 'candidate-scan',
    renderShape: 'list',
    docs: doc('Cleanup', ['scip-query not-implemented -s src/services']),
    handler: handleNotImplemented,
  }),
  heuristicCleanupCommand({
    id: 'decorative-checkers',
    command: 'decorative-checkers',
    agent: analysisAgentContract(
      'Which checker-named callables lack detected local failure syntax?',
      'checker identities, call sites, and decorative behavior evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      'Checker candidates lacking detected explicit failure syntax; implicit exceptions and property effects are not proved absent',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'decorative checker candidates',
    budget: 'candidate-scan',
    renderShape: 'list',
    docs: doc('Cleanup', ['scip-query decorative-checkers -s src/services']),
    handler: handleDecorativeCheckers,
  }),
  cleanupCommand({
    id: 'test-quality',
    command: 'test-quality',
    agent: analysisAgentContract(
      'Which test bodies lack detected assertions, remain skipped, or repeat mock literals?',
      'test identities with assertion, skip-age, and mock-literal evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      'Test-quality candidates: assertion-free it/test bodies, a skipped-test ledger with git-blame age, and mock-echo tests that assert the same literal they stubbed into a mock',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Maximum findings per sub-check', parseInteger, 30),
      option('--rot-days <n>', 'Skips older than this many days are reported as rot', parseInteger, 60),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'test-quality findings' },
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query test-quality -s tests/queries']),
    handler: handleTestQuality,
  }),
  cleanupCommand({
    id: 'similar-signatures',
    command: 'similar-signatures',
    agent: analysisAgentContract(
      'Which callables have suspiciously similar signatures?',
      'callable pairs with signature similarity evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      'Group functions by normalized signature text; shared type identity or responsibility is not established',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum LOC per function', parseInteger, 3),
      option(
        '--max-shape-frequency <n>',
        'Suppress noisy signature shapes above this frequency unless bodies match exactly',
        parseInteger,
        12,
      ),
      option('-n, --limit <n>', 'Number of groups', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    renderShape: 'list',
    handler: handleSimilarSignatures,
  }),
];
