import * as queries from '../../../queries/index.js';
import type { CommandDescriptor } from '../../command-kit/command-descriptor-types.js';
import { definedLimitOption, stringOptionValue } from '../../command-kit/command-execution.js';
import {
  agentContract,
  doc,
  option,
  parseInteger,
  parseNumber,
  parsePositiveInteger,
  withJsonOption,
} from '../../command-kit/command-spec-builders.js';
import { groupedQueryCommand } from '../../command-kit/query-command-builders.js';
import {
  handleUnusedParams,
  handleCleanupPlan,
  handleCleanupApply,
  handleRecentDuplicates,
  handleDocDrift,
  handleDead,
  handleUnusedImports,
  handleIsolated,
  handleSimilar,
  handleSimilarFiles,
  handleSimilarChains,
  handleExtractCandidates,
  handleLocalityCandidates,
  handleDrift,
  handleWrapperCandidates,
  handlePassthroughCandidates,
  handleStaleAbstractions,
  handleComplexityHotspots,
  handleConvergence,
  handleSimilarSignatures,
  handleDuplicateBodies,
  handleTwinDrift,
  handleTwinAb,
  handleNotImplemented,
  handleDecorativeCheckers,
  handleTestQuality,
} from './handlers.js';
import {
  handleReactComponentDuplicates,
  handleReactHookCandidates,
  handleReactLargeComponentPressure,
  handleVueComponentDuplicates,
  handleVueComposableCandidates,
  handleVueLargeViewPressure,
} from './frontend-handlers.js';

type CleanupCommandDescriptor = Omit<CommandDescriptor, 'docs'> & {
  docs?: CommandDescriptor['docs'];
};

type HeuristicCleanupCommandDescriptor = Omit<CleanupCommandDescriptor, 'heuristic'> & {
  heuristicLabel: string;
};

function cleanupCommand(descriptor: CleanupCommandDescriptor): CommandDescriptor {
  return {
    docs: doc('Cleanup'),
    ...descriptor,
  };
}

function heuristicCleanupCommand({
  heuristicLabel,
  ...descriptor
}: HeuristicCleanupCommandDescriptor): CommandDescriptor {
  return cleanupCommand({
    ...descriptor,
    heuristic: { label: heuristicLabel },
  });
}

export const cleanupQueryCommandDescriptors: CommandDescriptor[] = [
  cleanupCommand({
    id: 'unused-params',
    command: 'unused-params',
    agent: agentContract(
      'Which trailing parameters are never read by their bodies?',
      'candidate parameters with callable and file identities',
      [],
      'bounded',
      'repository',
    ),
    description: 'Speculative-generality candidates: trailing parameters no body ever uses (TS/JS)',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Maximum findings', parseInteger, 30),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'unused trailing parameter candidates' },
    renderShape: 'list',
    docs: doc('Cleanup', ['scip-query unused-params -s src/services']),
    handler: handleUnusedParams,
  }),
  cleanupCommand({
    id: 'cleanup-plan',
    command: 'cleanup-plan',
    agent: agentContract(
      'What code can be deleted safely, and in what dependency order?',
      'ordered cleanup batches, evidence, and optional verification outcomes',
      [],
      'bounded',
      'repository',
    ),
    description: 'Ordered, batched deletion plan: graph-fact dead code plus the cascade candidates it unlocks',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Only include symbols >= N lines', parseInteger, 1),
      option('--max-depth <n>', 'Maximum cascade depth', parseInteger, 5),
      option('--verify', 'Apply batches in a throwaway worktree and run the project checker (tsc / cargo check)'),
      option('--patch', 'With --verify, print the compiler-verified deletion patch to stdout'),
      option('--json', 'Output as JSON for programmatic consumption'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ],
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query cleanup-plan --min-loc 3', 'scip-query cleanup-plan --verify']),
    handler: handleCleanupPlan,
  }),
  cleanupCommand({
    id: 'cleanup-apply',
    command: 'cleanup-apply',
    agent: agentContract(
      'Can a compiler-verified cleanup batch be applied to this working tree?',
      'applied files, deletions, verification, and refusal reasons',
      [],
      'bounded',
      'repository',
    ),
    description: 'Apply a compiler-verified cleanup-plan batch to the working tree',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Only include symbols >= N lines', parseInteger, 1),
      option('--max-depth <n>', 'Maximum cascade depth', parseInteger, 5),
      option('--verified', 'Required: verify the selected cleanup batch before applying it'),
      option('--batch <n>', 'Apply one batch depth', parseInteger),
      option('--all', 'Apply every compiler-verified batch in the plan'),
      option('--force-dirty', 'Allow applying when plan files already have working-tree edits'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ],
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query cleanup-apply --verified --batch 0']),
    handler: handleCleanupApply,
  }),
  cleanupCommand({
    id: 'recent-duplicates',
    command: 'recent-duplicates',
    agent: agentContract(
      'Did recent code reimplement established code?',
      'recent and established symbol pairs with similarity evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      'Directional duplicate candidates: recent code that re-implements established callable, React, or Vue code',
    options: withJsonOption([
      option('--window <n>', 'How many commits back counts as "recent"', parseInteger, 100),
      option('--min-similarity <n>', 'Minimum similarity (0-1); omitted uses detector defaults', parseNumber),
      option('-n, --limit <n>', 'Maximum findings', parseInteger, 30),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded semantic and git-history analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'recent re-implementation candidates' },
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query recent-duplicates --window 50']),
    handler: handleRecentDuplicates,
  }),
  cleanupCommand({
    id: 'doc-drift',
    command: 'doc-drift [doc]',
    agent: agentContract(
      'Which documentation may be stale relative to changing code?',
      'document paths, coupled code subjects, and history evidence',
      ['path'],
      'bounded',
      'repository',
    ),
    description: 'Stale-doc candidates: code the doc references or co-changed with kept changing after the doc stopped',
    options: withJsonOption([
      option('-n, --limit <n>', 'Maximum docs to report', parseInteger, 20),
      option('--min-coupling <n>', 'Minimum historical co-changes to track a subject', parseInteger, 3),
      option('--full', 'Run unbounded git-history analysis on large indexes'),
    ]),
    heuristic: { label: 'doc drift candidates' },
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query doc-drift', 'scip-query doc-drift AGENTS.md']),
    handler: handleDocDrift,
  }),
  cleanupCommand({
    id: 'dead',
    command: 'dead [scope]',
    agent: agentContract(
      'Which symbols have no repository use or only file-internal use?',
      'symbol identities, ranges, liveness classes, and evidence',
      ['path'],
      'bounded',
      'repository',
    ),
    description: 'Find repository-dead code, file-internal symbols, and implicit-usage signals',
    options: withJsonOption([
      option('--min-loc <n>', 'Only show symbols >= N lines', parseInteger, 1),
      option('--include-tests', 'Include definitions from test files (test references always count)'),
      option('--skip-barrels', 'Ignore refs from barrel re-export files'),
      option('--include-members', 'Include class members'),
      option('--only-dead', 'Show only [dead code] symbols (skip file-internal and implicit-usage signals)'),
      option('--only-internal', 'Show only [file-internal only] symbols (skip dead-code and implicit-usage signals)'),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query dead --min-loc 10']),
    handler: handleDead,
  }),
  cleanupCommand({
    id: 'unused-imports',
    command: 'unused-imports <file>',
    agent: agentContract(
      'Which imports in this file are unused?',
      'import symbol identities and source ranges',
      ['file'],
      'bounded',
    ),
    description: 'Find imports not referenced in the same file',
    options: withJsonOption([option('--full', 'Run unbounded semantic analysis on large indexes')]),
    budget: 'semantic',
    renderShape: 'list',
    handler: handleUnusedImports,
  }),
  cleanupCommand({
    id: 'isolated',
    command: 'isolated',
    agent: agentContract(
      'Which symbols are disconnected from the repository reference graph?',
      'isolated symbol identities and files',
      [],
      'bounded',
      'repository',
    ),
    description: 'Find completely orphaned symbols (no references at all)',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum lines of code', parseInteger, 3),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    renderShape: 'grouped-by-file',
    handler: handleIsolated,
  }),
  heuristicCleanupCommand({
    id: 'similar',
    command: 'similar [symbol] [other]',
    agent: agentContract(
      'Which callable resembles this one, or how similar are these two?',
      'symbol pairs, similarity scores, and shared evidence',
      ['symbol', 'symbol'],
      'bounded',
      'repository',
    ),
    description: 'Find heuristic function similarity candidates from callee fingerprints',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum weighted-cosine similarity (0-1)', parseNumber, 0.4),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-callees <n>', 'Minimum callees to consider', parseInteger, 4),
      option('--cross-file-only', 'Only show cross-file pairs (skip same-file matches)'),
      option('--plan', 'Render a consolidation preview for two symbols'),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'similarity candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleSimilar,
  }),
  heuristicCleanupCommand({
    id: 'similar-files',
    command: 'similar-files [file]',
    agent: agentContract(
      'Which files have similar callable structure?',
      'file pairs with similarity scores and shared symbols',
      ['file'],
      'bounded',
      'repository',
    ),
    description: 'Find heuristic similar-file candidates from dependency profiles',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum Jaccard similarity (0-1)', parseNumber, 0.5),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-deps <n>', 'Minimum dependencies to consider', parseInteger),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'similar file candidates',
    renderShape: 'custom',
    handler: handleSimilarFiles,
  }),
  heuristicCleanupCommand({
    id: 'react-component-duplicates',
    command: 'react-component-duplicates [file]',
    agent: agentContract(
      'Which React components appear to duplicate one another?',
      'component pairs with structural similarity evidence',
      ['file'],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic duplicated React component structure candidates from JSX tags, props, events, and bindings',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum JSX structure similarity (0-1)', parseNumber, 0.62),
      option('--min-tokens <n>', 'Minimum structural tokens to consider', parseInteger, 8),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'React component duplicate candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleReactComponentDuplicates,
  }),
  heuristicCleanupCommand({
    id: 'react-hook-candidates',
    command: 'react-hook-candidates [file]',
    agent: agentContract(
      'Which repeated React logic could become a custom hook?',
      'component groups and shared hook-shaped behavior',
      ['file'],
      'bounded',
      'repository',
    ),
    description: 'Find heuristic React hook extraction candidates from shared state, effects, requests, and handlers',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum behavior similarity (0-1)', parseNumber, 0.45),
      option('--min-shared-behaviors <n>', 'Minimum shared behavior tokens', parseInteger, 6),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'React hook extraction candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleReactHookCandidates,
  }),
  heuristicCleanupCommand({
    id: 'react-large-component-pressure',
    command: 'react-large-component-pressure [file]',
    agent: agentContract(
      'Which React components have evidence of being too large or overloaded?',
      'component identities with size and responsibility pressure',
      ['file'],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic large React component pressure candidates from component lines, JSX structure, and hook behavior',
    options: withJsonOption([
      option('--min-component-lines <n>', 'Minimum component lines', parseInteger, 300),
      option('--min-file-lines <n>', 'Minimum file lines', parseInteger, 800),
      option('--min-jsx-tokens <n>', 'Minimum JSX structure tokens', parseInteger, 80),
      option('--min-behavior-tokens <n>', 'Minimum behavior tokens', parseInteger, 40),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'large React component pressure candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleReactLargeComponentPressure,
  }),
  heuristicCleanupCommand({
    id: 'vue-component-duplicates',
    command: 'vue-component-duplicates [file]',
    agent: agentContract(
      'Which Vue components appear to duplicate one another?',
      'component pairs with structural similarity evidence',
      ['file'],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic duplicated Vue component structure candidates from template tags, bindings, slots, and directives',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum template similarity (0-1)', parseNumber, 0.62),
      option('--min-tokens <n>', 'Minimum structural tokens to consider', parseInteger, 8),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'Vue component duplicate candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleVueComponentDuplicates,
  }),
  heuristicCleanupCommand({
    id: 'vue-composable-candidates',
    command: 'vue-composable-candidates [file]',
    agent: agentContract(
      'Which repeated Vue logic could become a composable?',
      'component groups and shared composable-shaped behavior',
      ['file'],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic Vue composable extraction candidates from shared state, effects, requests, and template bindings',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum behavior similarity (0-1)', parseNumber, 0.45),
      option('--min-shared-behaviors <n>', 'Minimum shared behavior tokens', parseInteger, 6),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'Vue composable extraction candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleVueComposableCandidates,
  }),
  heuristicCleanupCommand({
    id: 'vue-large-view-pressure',
    command: 'vue-large-view-pressure [file]',
    agent: agentContract(
      'Which Vue views have evidence of being too large or overloaded?',
      'view identities with size and responsibility pressure',
      ['file'],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic large Vue view pressure candidates from template, script, style, and external script line counts',
    options: withJsonOption([
      option('--min-total-lines <n>', 'Minimum total component lines', parseInteger, 800),
      option('--min-template-lines <n>', 'Minimum template lines', parseInteger, 300),
      option('--min-script-lines <n>', 'Minimum script lines', parseInteger, 300),
      option('--min-style-lines <n>', 'Minimum style lines', parseInteger, 500),
      option('--review-thresholds', 'Use lower review thresholds without changing health scoring'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'large Vue view pressure candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleVueLargeViewPressure,
  }),
  heuristicCleanupCommand({
    id: 'similar-chains',
    command: 'similar-chains',
    agent: agentContract(
      'Which transitive chains of similar symbols suggest repeated designs?',
      'similarity-connected symbol chains and scores',
      [],
      'bounded',
      'repository',
    ),
    description: 'Find heuristic similar-chain candidates from dependency flows',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum chain similarity (0-1)', parseNumber, 0.5),
      option('-n, --limit <n>', 'Number of results', parseInteger, 15),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-length <n>', 'Minimum chain length', parseInteger, 3),
      option('--max-length <n>', 'Maximum chain length', parseInteger, 8),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'similar chain candidates',
    renderShape: 'custom',
    handler: handleSimilarChains,
  }),
  heuristicCleanupCommand({
    id: 'extract-candidates',
    command: 'extract-candidates',
    agent: agentContract(
      'Which cohesive code regions are strong extraction candidates?',
      'symbol identities with cohesion, reuse, and extraction evidence',
      [],
      'bounded',
      'repository',
    ),
    description: 'Find heuristic extraction candidates from isolated callee clusters',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum function LOC', parseInteger, 10),
      option('--min-callees <n>', 'Minimum callees to analyze', parseInteger, 6),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'extraction candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleExtractCandidates,
  }),
  heuristicCleanupCommand({
    id: 'locality-candidates',
    command: 'locality-candidates [symbol-or-file]',
    agent: agentContract(
      'Which definitions live far from most of their consumers?',
      'symbols, current homes, consumer locality, and suggested homes',
      [['symbol', 'file']],
      'bounded',
      'repository',
    ),
    description: 'Find directory-locality and ancestry candidates from consumer ownership',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit scan mode to files matching path'),
      option('--min-consumers <n>', 'Minimum consumers in scan mode', parseInteger, 1),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'locality candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', [
      'scip-query locality-candidates',
      'scip-query locality-candidates formatName --json',
      'scip-query locality-candidates src/shared/date.ts',
    ]),
    handler: handleLocalityCandidates,
  }),
  heuristicCleanupCommand({
    id: 'drift',
    command: 'drift [module]',
    agent: agentContract(
      'Where has a module or abstraction drifted across parallel implementations?',
      'drifted symbol families, files, and evidence',
      ['module'],
      'bounded',
      'repository',
    ),
    description:
      'Detect drift candidates: unused imports and declared architecture violations; pass --architecture for boundary context',
    options: withJsonOption([
      option(
        '--min-deviation <n>',
        'Minimum sibling files before reporting unique dependency deviations',
        parsePositiveInteger,
        5,
      ),
      option(
        '--patterns',
        'Also include pattern-deviation findings ("only sibling importing X") — off by default: low precision at scale (21.2 calibration)',
        undefined,
        false,
      ),
      option(
        '--architecture',
        'Include boundary coverage, undeclared edges, reciprocal pairs, and connected groups',
        undefined,
        false,
      ),
      option('-n, --limit <n>', 'Number of results', parseInteger, 50),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'drift candidates',
    budget: 'semantic',
    renderShape: 'grouped-by-file',
    handler: handleDrift,
  }),
  heuristicCleanupCommand({
    id: 'wrapper-candidates',
    command: 'wrapper-candidates',
    agent: agentContract(
      'Which callables are unnecessary forwarding wrappers?',
      'wrapper identities, targets, and forwarding evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic wrapper candidates only called by one consumer (high false-positive rate on codebases with intentional layering/ambient types — treat as exploration, not findings)',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--max-loc <n>', 'Maximum LOC for candidates', parseInteger, 15),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'wrapper candidates',
    budget: 'candidate-scan',
    renderShape: 'list',
    handler: handleWrapperCandidates,
  }),
  heuristicCleanupCommand({
    id: 'passthrough-candidates',
    command: 'passthrough-candidates',
    agent: agentContract(
      'Which parameters are passed through layers without local use?',
      'parameter paths across call chains',
      [],
      'bounded',
      'repository',
    ),
    description: 'Find heuristic passthrough candidates that forward to one callee',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--max-loc <n>', 'Maximum LOC for candidates', parseInteger, 15),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'passthrough candidates',
    budget: 'candidate-scan',
    renderShape: 'list',
    handler: handlePassthroughCandidates,
  }),
  heuristicCleanupCommand({
    id: 'stale-abstractions',
    command: 'stale-abstractions',
    agent: agentContract(
      'Which abstractions no longer earn their indirection?',
      'abstraction identities with usage, change, and replacement evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      'Find heuristic stale abstraction candidates with 0-1 consumers (high false-positive rate on codebases with intentional layering/ambient types — treat as exploration, not findings)',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum LOC', parseInteger, 3),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option(
        '--include-low-confidence',
        'Include 1-consumer classes (usually encapsulation, not stale)',
        undefined,
        false,
      ),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'stale abstraction candidates',
    budget: 'candidate-scan',
    renderShape: 'list',
    handler: handleStaleAbstractions,
  }),
  heuristicCleanupCommand({
    id: 'complexity-hotspots',
    command: 'complexity-hotspots',
    agent: agentContract(
      'Which symbols combine high complexity with high change pressure?',
      'ranked symbols with complexity and churn evidence',
      [],
      'bounded',
      'repository',
    ),
    description: 'Find heuristic complexity hotspot candidates from LOC x fan-in x fan-out',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum LOC', parseInteger, 10),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'complexity hotspot candidates',
    budget: 'candidate-scan',
    renderShape: 'table',
    handler: handleComplexityHotspots,
  }),
  cleanupCommand({
    id: 'convergence',
    command: 'convergence <symbol1> <symbol2>',
    agent: agentContract(
      'How should these two similar symbols converge?',
      'deprecated alias result for a two-symbol similarity plan',
      ['symbol', 'symbol'],
      'bounded',
    ),
    evidence: 'heuristic',
    description: 'Deprecated alias for similar <symbol1> <symbol2> --plan',
    options: withJsonOption([option('--full', 'Run unbounded semantic analysis on large indexes')]),
    budget: 'semantic',
    renderShape: 'custom',
    handler: handleConvergence,
  }),
  groupedQueryCommand({
    id: 'redundant-reexports',
    command: 'redundant-reexports',
    agent: agentContract(
      'Which re-exports add no useful API boundary?',
      're-export sites, original definitions, and consumer evidence',
      [],
      'bounded',
      'repository',
    ),
    description: 'Find barrel re-exports that nobody imports through',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded analysis on large indexes'),
    ],
    docs: doc('Cleanup'),
    query: ({ db, opts }) =>
      queries.redundantReexports(db, {
        scope: stringOptionValue(opts, 'scope'),
        limit: definedLimitOption(opts, 'limit', 30),
      }),
    format: (r) =>
      `  ${r.shortName}  (from ${r.originalFile})\n` +
      `    barrel: ${r.barrelConsumers} consumer(s) | direct: ${r.directConsumers} consumer(s) | tier: ${r.actionTier}\n` +
      `    Recommendation: ${r.recommendation}` +
      (r.surfaceEvidence.length > 0 ? `\n    Surface evidence: ${r.surfaceEvidence.join('; ')}` : ''),
    key: (r) => r.barrelFile,
    emptyMessage: () => 'No redundant re-exports found.',
    after: (rows) => console.log(`\n${rows.length} redundant re-export(s).`),
  }),
  cleanupCommand({
    id: 'duplicate-bodies',
    command: 'duplicate-bodies',
    agent: agentContract(
      'Which callable bodies are exact duplicates?',
      'callable groups with exact normalized-body identity',
      [],
      'bounded',
      'repository',
    ),
    description: 'Find exact duplicate small-body candidates across files',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--max-loc <n>', 'Maximum LOC per function body', parseInteger, 15),
      option('--min-loc <n>', 'Minimum body LOC (excludes single-statement forwarding boilerplate)', parseInteger, 3),
      option('-n, --limit <n>', 'Number of groups', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'duplicate body candidates' },
    renderShape: 'list',
    handler: handleDuplicateBodies,
  }),
  cleanupCommand({
    id: 'twin-drift',
    command: 'twin-drift',
    agent: agentContract(
      'Which same-concept twin implementations have drifted?',
      'twin symbol pairs, history, and divergence evidence',
      [],
      'bounded',
      'repository',
    ),
    description: 'Twin drift candidates: same-name (or near-name) functions across files with diverged bodies',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option(
        '--min-similarity <n>',
        'Minimum normalized-token Jaccard similarity to report as divergent (0-1)',
        parseNumber,
        0.3,
      ),
      option('--include-homonyms', 'Also report same-name pairs below the similarity threshold (likely coincidental)'),
      option('-n, --limit <n>', 'Number of groups', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'twin drift candidates' },
    evidence: 'heuristic',
    renderShape: 'list',
    handler: handleTwinDrift,
  }),
  heuristicCleanupCommand({
    id: 'not-implemented',
    command: 'not-implemented',
    agent: agentContract(
      'Which callables are placeholders rather than real implementations?',
      'callable identities and placeholder evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      "Reachable placeholder stub candidates (throw-stub, TODO+return-default, empty body) — production callers can actually reach these; an unreachable stub is dead's job, not this one's",
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'reachable placeholder stubs',
    budget: 'candidate-scan',
    renderShape: 'list',
    docs: doc('Cleanup', ['scip-query not-implemented -s src/services']),
    handler: handleNotImplemented,
  }),
  heuristicCleanupCommand({
    id: 'decorative-checkers',
    command: 'decorative-checkers',
    agent: agentContract(
      'Which validation checks cannot meaningfully fail?',
      'checker identities, call sites, and decorative behavior evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      'Decorative checker candidates: validate*/verify*/check*/assert*/is*/has* callables with no reachable failure exit anywhere in their body',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'decorative checker candidates',
    budget: 'candidate-scan',
    renderShape: 'list',
    docs: doc('Cleanup', ['scip-query decorative-checkers -s src/services']),
    handler: handleDecorativeCheckers,
  }),
  cleanupCommand({
    id: 'test-quality',
    command: 'test-quality',
    agent: agentContract(
      'Which tests have weak assertions or poor production-code reach?',
      'test identities with assertion and reachability evidence',
      [],
      'bounded',
      'repository',
    ),
    description:
      'Test-quality candidates: assertion-free it/test bodies, a skipped-test ledger with git-blame age, and mock-echo tests that assert the same literal they stubbed into a mock',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Maximum findings per sub-check', parseInteger, 30),
      option('--rot-days <n>', 'Skips older than this many days are reported as rot', parseInteger, 60),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'test-quality findings' },
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query test-quality -s tests/queries']),
    handler: handleTestQuality,
  }),
  cleanupCommand({
    id: 'twin-ab',
    command: 'twin-ab <symbolA> <symbolB>',
    agent: agentContract(
      'How do these two twin implementations differ in structure and behavior?',
      'side-by-side symbol evidence and divergence classification',
      ['symbol', 'symbol'],
      'complete',
    ),
    description:
      'Generate a behavioral A/B scaffold comparing two same-concept twins (scip-audit integrity scenario) — a ready-to-fill vitest file, not an auto-executor',
    options: withJsonOption([
      option(
        '--out <path>',
        'Output path for the generated vitest file (default: tests/generated/twin-ab/<a>-vs-<b>.test.ts)',
      ),
      option('--force', 'Overwrite an existing scaffold file at the output path'),
    ]),
    evidence: 'heuristic',
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query twin-ab src/a.ts/escapeRegex src/b.ts/escapeRegExp']),
    handler: handleTwinAb,
  }),
  cleanupCommand({
    id: 'similar-signatures',
    command: 'similar-signatures',
    agent: agentContract(
      'Which callables have suspiciously similar signatures?',
      'callable pairs with signature similarity evidence',
      [],
      'bounded',
      'repository',
    ),
    description: 'Find functions with near-identical type signatures (same shape)',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum LOC per function', parseInteger, 3),
      option(
        '--max-shape-frequency <n>',
        'Suppress noisy signature shapes above this frequency unless bodies match exactly',
        parseInteger,
        12,
      ),
      option('-n, --limit <n>', 'Number of groups', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    renderShape: 'list',
    handler: handleSimilarSignatures,
  }),
];
