import * as queries from '../../../queries/index.js';
import type { CommandDescriptor } from '../../commands/command-descriptor-types.js';
import { definedLimitOption, stringOptionValue } from '../../commands/command-execution.js';
import {
  doc,
  option,
  parseInteger,
  parseNumber,
  parsePositiveInteger,
  withJsonOption,
} from '../../commands/command-spec-builders.js';
import { groupedQueryCommand } from '../../commands/query-command-builders.js';
import {
  handleUnusedParams,
  handleCleanupPlan,
  handleCleanupApply,
  handleRecentDuplicates,
  handleDocDrift,
  handleDead,
  handleUnusedImports,
  handleIsolated,
  handleSimilar,
  handleSimilarFiles,
  handleSimilarChains,
  handleExtractCandidates,
  handleLocalityCandidates,
  handleDrift,
  handleWrapperCandidates,
  handlePassthroughCandidates,
  handleStaleAbstractions,
  handleComplexityHotspots,
  handleConvergence,
  handleSimilarSignatures,
  handleDuplicateBodies,
  handleTwinDrift,
} from './handlers.js';
import {
  handleReactComponentDuplicates,
  handleReactHookCandidates,
  handleReactLargeComponentPressure,
  handleVueComponentDuplicates,
  handleVueComposableCandidates,
  handleVueLargeViewPressure,
} from './frontend-handlers.js';

type CleanupCommandDescriptor = Omit<CommandDescriptor, 'docs'> & {
  docs?: CommandDescriptor['docs'];
};

type HeuristicCleanupCommandDescriptor = Omit<CleanupCommandDescriptor, 'heuristic'> & {
  heuristicLabel: string;
};

function cleanupCommand(descriptor: CleanupCommandDescriptor): CommandDescriptor {
  return {
    docs: doc('Cleanup'),
    ...descriptor,
  };
}

function heuristicCleanupCommand({
  heuristicLabel,
  ...descriptor
}: HeuristicCleanupCommandDescriptor): CommandDescriptor {
  return cleanupCommand({
    ...descriptor,
    heuristic: { label: heuristicLabel },
  });
}

export const cleanupQueryCommandDescriptors: CommandDescriptor[] = [
  cleanupCommand({
    id: 'unused-params',
    command: 'unused-params',
    description: 'Speculative-generality candidates: trailing parameters no body ever uses (TS/JS)',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Maximum findings', parseInteger, 30),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'unused trailing parameter candidates' },
    renderShape: 'list',
    docs: doc('Cleanup', ['scip-query unused-params -s src/services']),
    handler: handleUnusedParams,
  }),
  cleanupCommand({
    id: 'cleanup-plan',
    command: 'cleanup-plan',
    description: 'Ordered, batched deletion plan: graph-fact dead code plus the cascade candidates it unlocks',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Only include symbols >= N lines', parseInteger, 1),
      option('--max-depth <n>', 'Maximum cascade depth', parseInteger, 5),
      option('--verify', 'Apply batches in a throwaway worktree and run the project checker (tsc / cargo check)'),
      option('--patch', 'With --verify, print the compiler-verified deletion patch to stdout'),
      option('--json', 'Output as JSON for programmatic consumption'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ],
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query cleanup-plan --min-loc 3', 'scip-query cleanup-plan --verify']),
    handler: handleCleanupPlan,
  }),
  cleanupCommand({
    id: 'cleanup-apply',
    command: 'cleanup-apply',
    description: 'Apply a compiler-verified cleanup-plan batch to the working tree',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Only include symbols >= N lines', parseInteger, 1),
      option('--max-depth <n>', 'Maximum cascade depth', parseInteger, 5),
      option('--verified', 'Required: verify the selected cleanup batch before applying it'),
      option('--batch <n>', 'Apply one batch depth', parseInteger),
      option('--all', 'Apply every compiler-verified batch in the plan'),
      option('--force-dirty', 'Allow applying when plan files already have working-tree edits'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ],
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query cleanup-apply --verified --batch 0']),
    handler: handleCleanupApply,
  }),
  cleanupCommand({
    id: 'recent-duplicates',
    command: 'recent-duplicates',
    description:
      'Directional duplicate candidates: recent code that re-implements established callable, React, or Vue code',
    options: withJsonOption([
      option('--window <n>', 'How many commits back counts as "recent"', parseInteger, 100),
      option('--min-similarity <n>', 'Minimum similarity (0-1); omitted uses detector defaults', parseNumber),
      option('-n, --limit <n>', 'Maximum findings', parseInteger, 30),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'recent re-implementation candidates' },
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query recent-duplicates --window 50']),
    handler: handleRecentDuplicates,
  }),
  cleanupCommand({
    id: 'doc-drift',
    command: 'doc-drift [doc]',
    description: 'Stale-doc candidates: code the doc references or co-changed with kept changing after the doc stopped',
    options: withJsonOption([
      option('-n, --limit <n>', 'Maximum docs to report', parseInteger, 20),
      option('--min-coupling <n>', 'Minimum historical co-changes to track a subject', parseInteger, 3),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristic: { label: 'doc drift candidates' },
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query doc-drift', 'scip-query doc-drift AGENTS.md']),
    handler: handleDocDrift,
  }),
  cleanupCommand({
    id: 'dead',
    command: 'dead [scope]',
    description: 'Find dead code and file-internal symbols (no cross-file consumers)',
    options: withJsonOption([
      option('--min-loc <n>', 'Only show symbols >= N lines', parseInteger, 1),
      option('--include-tests', 'Include test files'),
      option('--skip-barrels', 'Ignore refs from barrel re-export files'),
      option('--include-members', 'Include class members'),
      option('--only-dead', 'Show only [dead code] symbols (skip [file-internal only])'),
      option('--only-internal', 'Show only [file-internal only] symbols (skip [dead code])'),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', ['scip-query dead --min-loc 10']),
    handler: handleDead,
  }),
  cleanupCommand({
    id: 'unused-imports',
    command: 'unused-imports <file>',
    description: 'Find imports not referenced in the same file',
    options: withJsonOption([option('--full', 'Run unbounded semantic analysis on large indexes')]),
    budget: 'semantic',
    renderShape: 'list',
    handler: handleUnusedImports,
  }),
  cleanupCommand({
    id: 'isolated',
    command: 'isolated',
    description: 'Find completely orphaned symbols (no references at all)',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum lines of code', parseInteger, 3),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    renderShape: 'grouped-by-file',
    handler: handleIsolated,
  }),
  heuristicCleanupCommand({
    id: 'similar',
    command: 'similar [symbol] [other]',
    description: 'Find heuristic function similarity candidates from callee fingerprints',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum weighted-cosine similarity (0-1)', parseNumber, 0.4),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-callees <n>', 'Minimum callees to consider', parseInteger, 4),
      option('--cross-file-only', 'Only show cross-file pairs (skip same-file matches)'),
      option('--plan', 'Render a consolidation preview for two symbols'),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'similarity candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleSimilar,
  }),
  heuristicCleanupCommand({
    id: 'similar-files',
    command: 'similar-files [file]',
    description: 'Find heuristic similar-file candidates from dependency profiles',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum Jaccard similarity (0-1)', parseNumber, 0.5),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-deps <n>', 'Minimum dependencies to consider', parseInteger),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'similar file candidates',
    renderShape: 'custom',
    handler: handleSimilarFiles,
  }),
  heuristicCleanupCommand({
    id: 'react-component-duplicates',
    command: 'react-component-duplicates [file]',
    description:
      'Find heuristic duplicated React component structure candidates from JSX tags, props, events, and bindings',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum JSX structure similarity (0-1)', parseNumber, 0.62),
      option('--min-tokens <n>', 'Minimum structural tokens to consider', parseInteger, 8),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'React component duplicate candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleReactComponentDuplicates,
  }),
  heuristicCleanupCommand({
    id: 'react-hook-candidates',
    command: 'react-hook-candidates [file]',
    description: 'Find heuristic React hook extraction candidates from shared state, effects, requests, and handlers',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum behavior similarity (0-1)', parseNumber, 0.45),
      option('--min-shared-behaviors <n>', 'Minimum shared behavior tokens', parseInteger, 6),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'React hook extraction candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleReactHookCandidates,
  }),
  heuristicCleanupCommand({
    id: 'react-large-component-pressure',
    command: 'react-large-component-pressure [file]',
    description:
      'Find heuristic large React component pressure candidates from component lines, JSX structure, and hook behavior',
    options: withJsonOption([
      option('--min-component-lines <n>', 'Minimum component lines', parseInteger, 300),
      option('--min-file-lines <n>', 'Minimum file lines', parseInteger, 800),
      option('--min-jsx-tokens <n>', 'Minimum JSX structure tokens', parseInteger, 80),
      option('--min-behavior-tokens <n>', 'Minimum behavior tokens', parseInteger, 40),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'large React component pressure candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleReactLargeComponentPressure,
  }),
  heuristicCleanupCommand({
    id: 'vue-component-duplicates',
    command: 'vue-component-duplicates [file]',
    description:
      'Find heuristic duplicated Vue component structure candidates from template tags, bindings, slots, and directives',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum template similarity (0-1)', parseNumber, 0.62),
      option('--min-tokens <n>', 'Minimum structural tokens to consider', parseInteger, 8),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'Vue component duplicate candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleVueComponentDuplicates,
  }),
  heuristicCleanupCommand({
    id: 'vue-composable-candidates',
    command: 'vue-composable-candidates [file]',
    description:
      'Find heuristic Vue composable extraction candidates from shared state, effects, requests, and template bindings',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum behavior similarity (0-1)', parseNumber, 0.45),
      option('--min-shared-behaviors <n>', 'Minimum shared behavior tokens', parseInteger, 6),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'Vue composable extraction candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleVueComposableCandidates,
  }),
  heuristicCleanupCommand({
    id: 'vue-large-view-pressure',
    command: 'vue-large-view-pressure [file]',
    description:
      'Find heuristic large Vue view pressure candidates from template, script, style, and external script line counts',
    options: withJsonOption([
      option('--min-total-lines <n>', 'Minimum total component lines', parseInteger, 800),
      option('--min-template-lines <n>', 'Minimum template lines', parseInteger, 300),
      option('--min-script-lines <n>', 'Minimum script lines', parseInteger, 300),
      option('--min-style-lines <n>', 'Minimum style lines', parseInteger, 500),
      option('--review-thresholds', 'Use lower review thresholds without changing health scoring'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'large Vue view pressure candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleVueLargeViewPressure,
  }),
  heuristicCleanupCommand({
    id: 'similar-chains',
    command: 'similar-chains',
    description: 'Find heuristic similar-chain candidates from dependency flows',
    options: withJsonOption([
      option('--min-similarity <n>', 'Minimum chain similarity (0-1)', parseNumber, 0.5),
      option('-n, --limit <n>', 'Number of results', parseInteger, 15),
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-length <n>', 'Minimum chain length', parseInteger, 3),
      option('--max-length <n>', 'Maximum chain length', parseInteger, 8),
      option('--full', 'Run unbounded analysis on large indexes'),
    ]),
    heuristicLabel: 'similar chain candidates',
    renderShape: 'custom',
    handler: handleSimilarChains,
  }),
  heuristicCleanupCommand({
    id: 'extract-candidates',
    command: 'extract-candidates',
    description: 'Find heuristic extraction candidates from isolated callee clusters',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum function LOC', parseInteger, 10),
      option('--min-callees <n>', 'Minimum callees to analyze', parseInteger, 6),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'extraction candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    handler: handleExtractCandidates,
  }),
  heuristicCleanupCommand({
    id: 'locality-candidates',
    command: 'locality-candidates [symbol-or-file]',
    description: 'Find directory-locality and ancestry candidates from consumer ownership',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit scan mode to files matching path'),
      option('--min-consumers <n>', 'Minimum consumers in scan mode', parseInteger, 1),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'locality candidates',
    budget: 'candidate-scan',
    renderShape: 'custom',
    docs: doc('Cleanup', [
      'scip-query locality-candidates',
      'scip-query locality-candidates formatName --json',
      'scip-query locality-candidates src/shared/date.ts',
    ]),
    handler: handleLocalityCandidates,
  }),
  heuristicCleanupCommand({
    id: 'drift',
    command: 'drift [module]',
    description: 'Detect heuristic drift candidates: unused imports, layer violations, and pattern deviations',
    options: withJsonOption([
      option(
        '--min-deviation <n>',
        'Minimum sibling files before reporting unique dependency deviations',
        parsePositiveInteger,
        5,
      ),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'drift candidates',
    budget: 'semantic',
    renderShape: 'grouped-by-file',
    handler: handleDrift,
  }),
  heuristicCleanupCommand({
    id: 'wrapper-candidates',
    command: 'wrapper-candidates',
    description: 'Find heuristic wrapper candidates only called by one consumer',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--max-loc <n>', 'Maximum LOC for candidates', parseInteger, 15),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'wrapper candidates',
    budget: 'candidate-scan',
    renderShape: 'list',
    handler: handleWrapperCandidates,
  }),
  heuristicCleanupCommand({
    id: 'passthrough-candidates',
    command: 'passthrough-candidates',
    description: 'Find heuristic passthrough candidates that forward to one callee',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--max-loc <n>', 'Maximum LOC for candidates', parseInteger, 15),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'passthrough candidates',
    budget: 'candidate-scan',
    renderShape: 'list',
    handler: handlePassthroughCandidates,
  }),
  heuristicCleanupCommand({
    id: 'stale-abstractions',
    command: 'stale-abstractions',
    description: 'Find heuristic stale abstraction candidates with 0-1 consumers',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum LOC', parseInteger, 3),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option(
        '--include-low-confidence',
        'Include 1-consumer classes (usually encapsulation, not stale)',
        undefined,
        false,
      ),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'stale abstraction candidates',
    budget: 'candidate-scan',
    renderShape: 'list',
    handler: handleStaleAbstractions,
  }),
  heuristicCleanupCommand({
    id: 'complexity-hotspots',
    command: 'complexity-hotspots',
    description: 'Find heuristic complexity hotspot candidates from LOC x fan-in x fan-out',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum LOC', parseInteger, 10),
      option('-n, --limit <n>', 'Number of results', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    heuristicLabel: 'complexity hotspot candidates',
    budget: 'candidate-scan',
    renderShape: 'table',
    handler: handleComplexityHotspots,
  }),
  cleanupCommand({
    id: 'convergence',
    command: 'convergence <symbol1> <symbol2>',
    description: 'Deprecated alias for similar <symbol1> <symbol2> --plan',
    options: withJsonOption([option('--full', 'Run unbounded semantic analysis on large indexes')]),
    budget: 'semantic',
    renderShape: 'custom',
    handler: handleConvergence,
  }),
  groupedQueryCommand({
    id: 'redundant-reexports',
    command: 'redundant-reexports',
    description: 'Find barrel re-exports that nobody imports through',
    options: [
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('-n, --limit <n>', 'Number of results', parseInteger, 30),
      option('--full', 'Run unbounded analysis on large indexes'),
    ],
    docs: doc('Cleanup'),
    query: ({ db, opts }) =>
      queries.redundantReexports(db, {
        scope: stringOptionValue(opts, 'scope'),
        limit: definedLimitOption(opts, 'limit', 30),
      }),
    format: (r) =>
      `  ${r.shortName}  (from ${r.originalFile})\n` +
      `    barrel: ${r.barrelConsumers} consumer(s) | direct: ${r.directConsumers} consumer(s) | tier: ${r.actionTier}\n` +
      `    Recommendation: ${r.recommendation}` +
      (r.surfaceEvidence.length > 0 ? `\n    Surface evidence: ${r.surfaceEvidence.join('; ')}` : ''),
    key: (r) => r.barrelFile,
    emptyMessage: () => 'No redundant re-exports found.',
    after: (rows) => console.log(`\n${rows.length} redundant re-export(s).`),
  }),
  cleanupCommand({
    id: 'duplicate-bodies',
    command: 'duplicate-bodies',
    description: 'Find exact duplicate small-body candidates across files',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--max-loc <n>', 'Maximum LOC per function body', parseInteger, 15),
      option('-n, --limit <n>', 'Number of groups', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'duplicate body candidates' },
    renderShape: 'list',
    handler: handleDuplicateBodies,
  }),
  cleanupCommand({
    id: 'twin-drift',
    command: 'twin-drift',
    description: 'Twin drift candidates: same-name (or near-name) functions across files with diverged bodies',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option(
        '--min-similarity <n>',
        'Minimum normalized-token Jaccard similarity to report as divergent (0-1)',
        parseNumber,
        0.3,
      ),
      option('--include-homonyms', 'Also report same-name pairs below the similarity threshold (likely coincidental)'),
      option('-n, --limit <n>', 'Number of groups', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    heuristic: { label: 'twin drift candidates' },
    evidence: 'heuristic',
    renderShape: 'list',
    handler: handleTwinDrift,
  }),
  cleanupCommand({
    id: 'similar-signatures',
    command: 'similar-signatures',
    description: 'Find functions with near-identical type signatures (same shape)',
    options: withJsonOption([
      option('-s, --scope <path>', 'Limit to files matching path'),
      option('--min-loc <n>', 'Minimum LOC per function', parseInteger, 3),
      option(
        '--max-shape-frequency <n>',
        'Suppress noisy signature shapes above this frequency unless bodies match exactly',
        parseInteger,
        12,
      ),
      option('-n, --limit <n>', 'Number of groups', parseInteger, 20),
      option('--full', 'Run unbounded semantic analysis on large indexes'),
    ]),
    budget: 'candidate-scan',
    renderShape: 'list',
    handler: handleSimilarSignatures,
  }),
];
