import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { commandDescriptors } from '../src/runtime/commands/command-descriptors.js';
import { descriptorClaimContract, renderCommandReferenceMarkdown } from '../src/runtime/command-kit/command-docs.js';
import type { CommandDescriptor } from '../src/runtime/command-kit/command-descriptor-types.js';
import {
  explorationControlManualRows,
  renderExplorationManualAgentLines,
  renderExplorationManualMarkdown,
  renderExplorationSkillGuideMarkdown,
} from '../src/runtime/command-kit/exploration-manual.js';
import { commandOperationRoles } from '../src/runtime/command-operation.js';
import { renderDetectorEvidenceContractsMarkdown } from '../src/queries/health/detector-evidence-contracts.js';

const generated = renderCommandReferenceMarkdown(commandDescriptors);

export function renderAgentSetupCommandCatalogSource(
  descriptors: readonly CommandDescriptor[] = commandDescriptors,
): string {
  const lines = renderExplorationManualAgentLines(descriptors);
  const sourceEntries = lines.map((line) => {
    const literal = line
      .replaceAll('\\', '\\\\')
      .replaceAll("'", "\\'")
      .replaceAll('\n', '\\n')
      .replaceAll('\r', '\\r');
    return `  '${literal}',`;
  });
  const controlRows = JSON.stringify(explorationControlManualRows(descriptors), null, 2);
  return [
    '// Generated by scripts/render-command-reference.ts. Do not edit by hand.',
    '// prettier-ignore',
    'export const GENERATED_AGENT_COMMAND_CATALOG = [',
    ...sourceEntries,
    '] as const;',
    '',
    '// prettier-ignore',
    `export const GENERATED_EXPLORATION_CONTROLS = ${controlRows} as const;`,
    '',
  ].join('\n');
}

function replaceGeneratedBlock(path: string, label: string, content: string): void {
  const current = readFileSync(path, 'utf8');
  const pattern = new RegExp(`<!-- BEGIN GENERATED ${label} -->[\\s\\S]*?<!-- END GENERATED ${label} -->`);
  if (!pattern.test(current)) return;
  writeFileSync(path, current.replace(pattern, content));
}

// ── Per-skill command allowlist (Plan 3, 19.1) ─────────────────────────────
//
// Each skill's SKILL.md frontmatter may declare a `commands:` list of exact
// invocation templates, e.g.:
//
//   commands:
//     - template: "scip-query twin-drift -s <scope> --json"
//       when: "Run the detector over the group's scope."
//
// This generator validates every template's base command and flags against
// `commandDescriptors` (unknown command/flag fails the build — the same
// guarantee the full catalog has) and renders a marker-delimited
// "## Commands for this skill" block into the skill body. Skills without a
// `commands:` key are skipped.

export interface SkillCommandEntry {
  template: string;
  when: string;
}

const SKILL_COMMANDS_BEGIN = '<!-- BEGIN GENERATED SKILL COMMANDS -->';
const SKILL_COMMANDS_END = '<!-- END GENERATED SKILL COMMANDS -->';

function writeSkillCommandBlocks(skillsRoot: string): void {
  for (const entry of readdirSync(skillsRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const skillMdPath = join(skillsRoot, entry.name, 'SKILL.md');
    try {
      if (!statSync(skillMdPath).isFile()) continue;
    } catch {
      continue;
    }
    const raw = readFileSync(skillMdPath, 'utf8');
    const commands = parseSkillCommands(raw, `skills/${entry.name}/SKILL.md`);
    if (commands.length === 0) continue;
    for (const command of commands) validateSkillCommand(command, `skills/${entry.name}/SKILL.md`);
    const block = renderSkillCommandsMarkdown(commands);
    const updated = spliceGeneratedBlock(raw, SKILL_COMMANDS_BEGIN, SKILL_COMMANDS_END, block);
    if (updated !== raw) writeFileSync(skillMdPath, updated);
  }
}

export function parseSkillCommands(raw: string, sourceLabel: string): SkillCommandEntry[] {
  const frontmatterMatch = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!frontmatterMatch) return [];
  const frontmatter = frontmatterMatch[1] ?? '';
  const lines = frontmatter.split('\n');
  const startIndex = lines.findIndex((line) => /^commands:\s*$/.test(line));
  if (startIndex === -1) return [];

  const entries: SkillCommandEntry[] = [];
  let current: Partial<SkillCommandEntry> | null = null;
  for (const line of lines.slice(startIndex + 1)) {
    if (/^\S/.test(line)) break; // dedent — next top-level frontmatter key
    // Quote style is not ours to control here: `npm run format` (prettier's
    // YAML formatter) rewrites frontmatter string quoting per-line — single
    // quotes by default, double only when the value itself contains an
    // apostrophe (e.g. "the model's Next relation"). Both quote styles must
    // parse, or a plain `prettier --write` silently empties a skill's
    // commands list (this once broke a routed TLA+ skill preview row).
    const templateMatch = line.match(/^  - template:\s*(?:"(.*)"|'(.*)')\s*$/);
    const whenMatch = line.match(/^    when:\s*(?:"(.*)"|'(.*)')\s*$/);
    if (templateMatch) {
      if (current?.template) entries.push(finishSkillCommandEntry(current, sourceLabel));
      current = { template: templateMatch[1] ?? templateMatch[2] };
    } else if (whenMatch && current) {
      current.when = whenMatch[1] ?? whenMatch[2];
    } else if (line.trim().length > 0) {
      throw new Error(`${sourceLabel}: malformed commands frontmatter line: ${line.trim()}`);
    }
  }
  if (current?.template) entries.push(finishSkillCommandEntry(current, sourceLabel));
  return entries;
}

function finishSkillCommandEntry(entry: Partial<SkillCommandEntry>, sourceLabel: string): SkillCommandEntry {
  if (!entry.template) throw new Error(`${sourceLabel}: commands entry missing template`);
  if (!entry.when) throw new Error(`${sourceLabel}: commands entry "${entry.template}" missing when`);
  return { template: entry.template, when: entry.when };
}

function skillCommandTokens(template: string): string[] {
  const withoutPrefix = template.replace(/^scip-query\s+/, '');
  return withoutPrefix.split(/\s+/).filter(Boolean);
}

function findDescriptorForCommandId(commandId: string): CommandDescriptor | undefined {
  return commandDescriptors.find((descriptor) => descriptor.command.split(/\s+/)[0] === commandId);
}

export function validateSkillCommand(entry: SkillCommandEntry, sourceLabel: string): void {
  const tokens = skillCommandTokens(entry.template);
  const commandId = tokens[0];
  const descriptor = commandId ? findDescriptorForCommandId(commandId) : undefined;
  if (!descriptor) {
    throw new Error(`${sourceLabel}: unknown command "${commandId ?? entry.template}" in commands frontmatter`);
  }
  const knownFlags = new Set<string>();
  for (const opt of descriptor.options ?? []) {
    for (const part of opt.flags.split(',')) {
      const flag = part.trim().split(/\s+/)[0];
      if (flag) knownFlags.add(flag);
    }
  }
  for (const token of tokens.slice(1)) {
    if (!token.startsWith('-')) continue;
    if (!knownFlags.has(token)) {
      throw new Error(
        `${sourceLabel}: unknown flag "${token}" for command "${commandId}" (template: ${entry.template})`,
      );
    }
  }
}

function escapeSkillTableCell(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('|', '\\|');
}

export function renderAgentContractCatalogMarkdown(
  descriptors: readonly CommandDescriptor[] = commandDescriptors,
): string {
  const rows = [
    '<!-- BEGIN GENERATED AGENT CONTRACT CATALOG -->',
    '| Command | Questions it answers | Returns | Operation role(s) | Default coverage | Claim origin | Observed sources | Producer validation | Mixed-family bindings |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
  ];
  for (const descriptor of descriptors.filter((entry) => !entry.hidden)) {
    const contract = descriptor.agent;
    const claims = descriptorClaimContract(descriptor);
    rows.push(
      `| \`scip-query ${descriptor.command}\` | ${escapeSkillTableCell(
        contract?.answers.join('; ') ?? 'Undeclared',
      )} | ${escapeSkillTableCell(contract?.returns.join('; ') ?? 'Undeclared')} | ${
        contract
          ? commandOperationRoles(contract.operation)
              .map((role) => `\`${role}\``)
              .join('<br>')
          : 'Undeclared'
      } | \`${contract?.coverage ?? 'unknown'}\` | \`${claims.origin}\` | ${claims.observedSources
        .map((source) => `\`${source}\``)
        .join('<br>')} | \`${claims.producerValidation.status}\` | ${
        claims.families?.map((family) => `\`${family.id}\` → \`${family.selector}\``).join('<br>') ?? '-'
      } |`,
    );
  }
  rows.push('<!-- END GENERATED AGENT CONTRACT CATALOG -->');
  return rows.join('\n');
}

export function renderSkillCommandsMarkdown(commands: readonly SkillCommandEntry[]): string {
  const rows = [
    SKILL_COMMANDS_BEGIN,
    '## Commands for this skill',
    '',
    '| Command | When |',
    '| --- | --- |',
    ...commands.map((entry) => `| \`${entry.template}\` | ${escapeSkillTableCell(entry.when)} |`),
    '',
    "Use this shortlist first. Run a command's `--help` only when a named uncertainty needs another option.",
    SKILL_COMMANDS_END,
  ];
  return rows.join('\n');
}

function spliceGeneratedBlock(raw: string, beginMarker: string, endMarker: string, block: string): string {
  const pattern = new RegExp(
    `${beginMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${endMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`,
  );
  if (pattern.test(raw)) return raw.replace(pattern, block);

  const lines = raw.split('\n');
  const sharedLineIndex = lines.findIndex((line) => line.includes('Load shared mechanics'));
  const headingIndex = lines.findIndex((line) => line.startsWith('# '));
  const insertAt = sharedLineIndex !== -1 ? sharedLineIndex + 1 : headingIndex !== -1 ? headingIndex + 1 : lines.length;
  lines.splice(insertAt, 0, '', block);
  return lines.join('\n');
}

// Skip all top-level side effects when this module is imported by the test
// runner (Vitest sets VITEST=true) — a unit test importing the pure
// parse/validate/render functions below must not print or write anything.
const isTestImport = process.env['VITEST'] === 'true';

if (!isTestImport && process.argv.includes('--write')) {
  replaceGeneratedBlock(join(process.cwd(), 'docs/COMMAND_REFERENCE.md'), 'COMMAND REFERENCE', generated);
  writeFileSync(join(process.cwd(), 'docs/DETECTOR_EVIDENCE_CONTRACTS.md'), renderDetectorEvidenceContractsMarkdown());
  if (process.argv.includes('--docs-only')) process.exit(0);
  writeFileSync(
    join(process.cwd(), 'src/runtime/generated-agent-command-catalog.ts'),
    renderAgentSetupCommandCatalogSource(commandDescriptors),
  );
  replaceGeneratedBlock(
    join(process.cwd(), 'skills/scip-query/SKILL.md'),
    'EXPLORATION MANUAL',
    [
      '<!-- BEGIN GENERATED EXPLORATION MANUAL -->',
      renderExplorationSkillGuideMarkdown(commandDescriptors),
      '<!-- END GENERATED EXPLORATION MANUAL -->',
    ].join('\n'),
  );
  writeSkillCommandBlocks(join(process.cwd(), 'skills'));
} else if (!isTestImport) {
  console.log(generated);
}
